import { NextResponse } from "next/server";
import { createSupabaseSessionClient } from "@/infrastructure/supabase/session-client";
import { getTenantScopeForUser } from "@/infrastructure/supabase/tenant-context-server";
import { getSupabaseAdmin } from "@/infrastructure/supabase/server-client";
import { can,isStaffRole } from "@/shared/auth/permissions";

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
async function requireWrite(){const session=await createSupabaseSessionClient();const {data}=await session.auth.getUser();if(!data.user)return {response:NextResponse.json({error:"Sesión requerida"},{status:401})};const tenant=await getTenantScopeForUser(data.user.id);const profile=await session.schema("api").from("t_perfiles").select("f_rol").eq("f_uuid",data.user.id).maybeSingle();if(profile.error||!isStaffRole(profile.data?.f_rol)||!can(profile.data.f_rol,"reservations:write"))return {response:NextResponse.json({error:"No autorizado"},{status:403})};return {actorId:data.user.id,tenant};}
function reservationError(error:unknown){const message=error instanceof Error?error.message:"";const safe=["Cantidad de reserva inválida","Vencimiento de reserva inválido","Sucursal inválida","Sucursal no autorizada","Paciente inválido","Producto inválido","Inventario disponible insuficiente","Inventario disponible cambió durante la reserva"].find(item=>message.includes(item));return NextResponse.json({error:safe??"No se pudo crear la reserva"},{status:safe?400:500});}

export async function POST(request:Request){const auth=await requireWrite();if("response" in auth)return auth.response;try{const input=await request.json() as Record<string,unknown>;const patientId=String(input.patientId??"");const productId=String(input.productId??"");const branchId=String(input.branchId??"");const quantity=Number(input.quantity);const expiresAt=String(input.expiresAt??"");if(!uuid.test(patientId)||!uuid.test(productId)||!uuid.test(branchId)||!Number.isFinite(quantity)||quantity<=0||!expiresAt||Number.isNaN(Date.parse(expiresAt)))throw new Error("Datos de reserva inválidos");const {data,error}=await getSupabaseAdmin().schema("api").rpc("fn_crear_reserva",{p_actor_uuid:auth.actorId,p_uuid_paciente:patientId,p_uuid_producto:productId,p_uuid_sucursal:branchId,p_cantidad:quantity,p_expira_en:new Date(expiresAt).toISOString(),p_referencia:null});if(error)throw new Error(error.message);return NextResponse.json({id:data},{status:201});}catch(error){if(error instanceof Error&&error.message==="Datos de reserva inválidos")return NextResponse.json({error:error.message},{status:400});return reservationError(error);}}
