begin;

create or replace function api.fn_normalizar_codigo_mantenimiento(p_valor text)
returns text language sql immutable as $$
  select upper(regexp_replace(trim(coalesce(p_valor,'')),'[^A-Za-z0-9ÁÉÍÓÚÜÑáéíóúüñ]+','_','g'))
$$;

create table if not exists api.t_categorias_productos (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(160) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_categorias_productos_pkey primary key(f_uuid)
);
create table if not exists api.t_fabricantes_productos (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(160) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_fabricantes_productos_pkey primary key(f_uuid)
);
create table if not exists api.t_principios_activos (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(200) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_principios_activos_pkey primary key(f_uuid)
);
create table if not exists api.t_unidades_medida (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(100) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_unidades_medida_pkey primary key(f_uuid)
);
create table if not exists api.t_formas_farmaceuticas (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(120) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_formas_farmaceuticas_pkey primary key(f_uuid)
);
create table if not exists api.t_vias_administracion (
  f_id bigint generated by default as identity not null,
  f_id_secuencia bigint generated by default as identity not null,
  f_uuid uuid not null default gen_random_uuid(),
  f_email_principal character varying(180) not null default 'pendiente@local.dev',
  f_rnc_principal character varying(20) not null default 'PENDIENTE',
  f_idempresa integer not null default 4,
  f_idsucursal integer not null default 1,
  f_app integer not null default 0,
  f_codigo character varying(60) not null,
  f_nombre character varying(120) not null,
  f_descripcion text,
  f_activo boolean not null default true,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  constraint t_vias_administracion_pkey primary key(f_uuid)
);

do $$ declare t text; begin
  foreach t in array array['t_categorias_productos','t_fabricantes_productos','t_principios_activos','t_unidades_medida','t_formas_farmaceuticas','t_vias_administracion'] loop
    execute format('create unique index if not exists ux_%s_f_id on api.%I(f_id)',t,t);
    execute format('create unique index if not exists ux_%s_tenant_codigo on api.%I(f_idempresa,f_idsucursal,f_app,f_codigo)',t,t);
    execute format('create index if not exists ix_%s_tenant_activo on api.%I(f_idempresa,f_idsucursal,f_app,f_activo)',t,t);
    execute format('alter table api.%I enable row level security',t);
    execute format('grant select,insert,update on api.%I to service_role',t);
  end loop;
end $$;

alter table api.t_productos add column if not exists f_uuid_categoria uuid;
alter table api.t_productos add column if not exists f_uuid_fabricante uuid;
alter table api.t_productos add column if not exists f_uuid_principio_activo uuid;
alter table api.t_productos add column if not exists f_uuid_unidad_medida uuid;
alter table api.t_productos add column if not exists f_uuid_forma_farmaceutica uuid;
alter table api.t_productos add column if not exists f_uuid_via_administracion uuid;

alter table api.t_productos drop constraint if exists fk_t_productos_categoria;
alter table api.t_productos add constraint fk_t_productos_categoria foreign key(f_uuid_categoria) references api.t_categorias_productos(f_uuid);
alter table api.t_productos drop constraint if exists fk_t_productos_fabricante;
alter table api.t_productos add constraint fk_t_productos_fabricante foreign key(f_uuid_fabricante) references api.t_fabricantes_productos(f_uuid);
alter table api.t_productos drop constraint if exists fk_t_productos_principio;
alter table api.t_productos add constraint fk_t_productos_principio foreign key(f_uuid_principio_activo) references api.t_principios_activos(f_uuid);
alter table api.t_productos drop constraint if exists fk_t_productos_unidad;
alter table api.t_productos add constraint fk_t_productos_unidad foreign key(f_uuid_unidad_medida) references api.t_unidades_medida(f_uuid);
alter table api.t_productos drop constraint if exists fk_t_productos_forma;
alter table api.t_productos add constraint fk_t_productos_forma foreign key(f_uuid_forma_farmaceutica) references api.t_formas_farmaceuticas(f_uuid);
alter table api.t_productos drop constraint if exists fk_t_productos_via;
alter table api.t_productos add constraint fk_t_productos_via foreign key(f_uuid_via_administracion) references api.t_vias_administracion(f_uuid);

with tenants as (
  select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal
  from api.t_productos order by f_idempresa,f_idsucursal,f_app
)
insert into api.t_categorias_productos(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select v.codigo,v.nombre,v.descripcion,t.f_email_principal,t.f_rnc_principal,t.f_idempresa,t.f_idsucursal,t.f_app
from tenants t cross join (values
 ('SIN_CLASIFICAR','SIN CLASIFICAR','Producto pendiente de clasificación'),
 ('MEDICAMENTOS','MEDICAMENTOS','Productos farmacéuticos'),
 ('CUIDADO_PERSONAL','CUIDADO PERSONAL','Higiene y cuidado personal'),
 ('DISPOSITIVOS_MEDICOS','DISPOSITIVOS MÉDICOS','Dispositivos e insumos médicos'),
 ('SUPLEMENTOS','SUPLEMENTOS','Vitaminas y suplementos'),
 ('OTROS','OTROS','Otros productos')
) v(codigo,nombre,descripcion)
on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;

with tenants as (select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal from api.t_productos order by f_idempresa,f_idsucursal,f_app)
insert into api.t_fabricantes_productos(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select 'NO_INFORMADO','NO INFORMADO','Fabricante pendiente de identificación',f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app from tenants
on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;
with tenants as (select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal from api.t_productos order by f_idempresa,f_idsucursal,f_app)
insert into api.t_principios_activos(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select 'NO_INFORMADO','NO INFORMADO','Principio activo pendiente de identificación',f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app from tenants
on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;

with tenants as (select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal from api.t_productos order by f_idempresa,f_idsucursal,f_app)
insert into api.t_unidades_medida(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select v.codigo,v.nombre,null,t.f_email_principal,t.f_rnc_principal,t.f_idempresa,t.f_idsucursal,t.f_app from tenants t cross join (values
 ('NO_INFORMADA','NO INFORMADA'),('UNIDAD','UNIDAD'),('CAJA','CAJA'),('FRASCO','FRASCO'),('BLISTER','BLÍSTER'),('TUBO','TUBO'),('AMPOLLA','AMPOLLA'),('SOBRE','SOBRE'),('GOTERO','GOTERO')
) v(codigo,nombre) on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;
with tenants as (select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal from api.t_productos order by f_idempresa,f_idsucursal,f_app)
insert into api.t_formas_farmaceuticas(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select v.codigo,v.nombre,null,t.f_email_principal,t.f_rnc_principal,t.f_idempresa,t.f_idsucursal,t.f_app from tenants t cross join (values
 ('NO_INFORMADA','NO INFORMADA'),('TABLETA','TABLETA'),('CAPSULA','CÁPSULA'),('JARABE','JARABE'),('CREMA','CREMA'),('SOLUCION','SOLUCIÓN'),('SUSPENSION','SUSPENSIÓN'),('GOTAS','GOTAS'),('INYECTABLE','INYECTABLE'),('POLVO','POLVO'),('GEL','GEL'),('OTRA','OTRA')
) v(codigo,nombre) on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;
with tenants as (select distinct on(f_idempresa,f_idsucursal,f_app) f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal from api.t_productos order by f_idempresa,f_idsucursal,f_app)
insert into api.t_vias_administracion(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
select v.codigo,v.nombre,null,t.f_email_principal,t.f_rnc_principal,t.f_idempresa,t.f_idsucursal,t.f_app from tenants t cross join (values
 ('NO_INFORMADA','NO INFORMADA'),('ORAL','ORAL'),('TOPICA','TÓPICA'),('OFTALMICA','OFTÁLMICA'),('OTICA','ÓTICA'),('NASAL','NASAL'),('VAGINAL','VAGINAL'),('RECTAL','RECTAL'),('INHALATORIA','INHALATORIA'),('INYECTABLE','INYECTABLE'),('OTRA','OTRA')
) v(codigo,nombre) on conflict(f_idempresa,f_idsucursal,f_app,f_codigo) do nothing;

update api.t_productos p set
 f_uuid_categoria=(select f_uuid from api.t_categorias_productos m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='SIN_CLASIFICAR'),
 f_uuid_fabricante=(select f_uuid from api.t_fabricantes_productos m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='NO_INFORMADO'),
 f_uuid_principio_activo=(select f_uuid from api.t_principios_activos m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='NO_INFORMADO'),
 f_uuid_unidad_medida=(select f_uuid from api.t_unidades_medida m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='NO_INFORMADA'),
 f_uuid_forma_farmaceutica=(select f_uuid from api.t_formas_farmaceuticas m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='NO_INFORMADA'),
 f_uuid_via_administracion=(select f_uuid from api.t_vias_administracion m where m.f_idempresa=p.f_idempresa and m.f_idsucursal=p.f_idsucursal and m.f_app=p.f_app and m.f_codigo='NO_INFORMADA')
where f_uuid_categoria is null or f_uuid_fabricante is null or f_uuid_principio_activo is null or f_uuid_unidad_medida is null or f_uuid_forma_farmaceutica is null or f_uuid_via_administracion is null;

create or replace function api.fn_completar_catalogos_producto()
returns trigger language plpgsql set search_path=api,public as $$
begin
 new.f_uuid_categoria := coalesce(new.f_uuid_categoria,(select f_uuid from api.t_categorias_productos where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='SIN_CLASIFICAR'));
 new.f_uuid_fabricante := coalesce(new.f_uuid_fabricante,(select f_uuid from api.t_fabricantes_productos where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='NO_INFORMADO'));
 new.f_uuid_principio_activo := coalesce(new.f_uuid_principio_activo,(select f_uuid from api.t_principios_activos where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='NO_INFORMADO'));
 new.f_uuid_unidad_medida := coalesce(new.f_uuid_unidad_medida,(select f_uuid from api.t_unidades_medida where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='NO_INFORMADA'));
 new.f_uuid_forma_farmaceutica := coalesce(new.f_uuid_forma_farmaceutica,(select f_uuid from api.t_formas_farmaceuticas where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='NO_INFORMADA'));
 new.f_uuid_via_administracion := coalesce(new.f_uuid_via_administracion,(select f_uuid from api.t_vias_administracion where f_idempresa=new.f_idempresa and f_idsucursal=new.f_idsucursal and f_app=new.f_app and f_codigo='NO_INFORMADA'));
 return new;
end $$;
drop trigger if exists tr_completar_catalogos_producto on api.t_productos;
create trigger tr_completar_catalogos_producto before insert on api.t_productos for each row execute function api.fn_completar_catalogos_producto();

alter table api.t_productos alter column f_uuid_categoria set not null;
alter table api.t_productos alter column f_uuid_fabricante set not null;
alter table api.t_productos alter column f_uuid_principio_activo set not null;
alter table api.t_productos alter column f_uuid_unidad_medida set not null;
alter table api.t_productos alter column f_uuid_forma_farmaceutica set not null;
alter table api.t_productos alter column f_uuid_via_administracion set not null;

create or replace function api.fn_crear_mantenimiento_inventario(p_actor_uuid uuid,p_tipo text,p_codigo text,p_nombre text,p_descripcion text default null)
returns uuid language plpgsql security definer set search_path=api,public as $$
declare v_empresa integer; v_sucursal integer; v_app integer; v_email varchar(180); v_rnc varchar(20); v_tabla text; v_uuid uuid;
begin
 select f_idempresa,f_idsucursal,f_app,f_email_principal,f_rnc_principal into v_empresa,v_sucursal,v_app,v_email,v_rnc from api.t_perfiles where f_uuid=p_actor_uuid and f_activo and f_rol in ('administrator','inventory');
 if not found then raise exception 'Permiso de inventario requerido'; end if;
 v_tabla := case p_tipo when 'category' then 't_categorias_productos' when 'manufacturer' then 't_fabricantes_productos' when 'activeIngredient' then 't_principios_activos' when 'unit' then 't_unidades_medida' when 'dosageForm' then 't_formas_farmaceuticas' when 'route' then 't_vias_administracion' end;
 if v_tabla is null then raise exception 'Tipo de mantenimiento inválido'; end if;
 if length(trim(coalesce(p_nombre,'')))<2 or length(trim(p_nombre))>200 then raise exception 'Nombre de mantenimiento inválido'; end if;
 execute format('insert into api.%I(f_codigo,f_nombre,f_descripcion,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app) values($1,upper(trim($2)),nullif(trim(coalesce($3,'''')),''''),$4,$5,$6,$7,$8) returning f_uuid',v_tabla)
 into v_uuid using api.fn_normalizar_codigo_mantenimiento(coalesce(nullif(trim(p_codigo),''),p_nombre)),p_nombre,p_descripcion,v_email,v_rnc,v_empresa,v_sucursal,v_app;
 insert into api.t_eventos_auditoria(f_uuid_actor,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,f_metadatos_seguros,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
 values(p_actor_uuid,'inventory.maintenance_created',p_tipo,v_uuid,gen_random_uuid(),jsonb_build_object('type',p_tipo),v_email,v_rnc,v_empresa,v_sucursal,v_app);
 return v_uuid;
exception when unique_violation then raise exception 'Código de mantenimiento ya existe';
end $$;

create or replace function api.fn_crear_producto_inventario_relacional(
 p_actor_uuid uuid,p_codigo text,p_nombre text,p_presentacion text,p_codigo_barras text,p_uuid_categoria uuid,p_uuid_fabricante uuid,p_uuid_principio_activo uuid,p_uuid_unidad_medida uuid,p_uuid_forma_farmaceutica uuid,p_uuid_via_administracion uuid,p_registro_sanitario text,p_requiere_receta boolean,p_posiciones jsonb
) returns uuid language plpgsql security definer set search_path=api,public as $$
declare v_empresa integer; v_sucursal integer; v_app integer; v_categoria text; v_fabricante text; v_principio text; v_unidad text; v_producto uuid; v_dummy text;
begin
 select f_idempresa,f_idsucursal,f_app into v_empresa,v_sucursal,v_app from api.t_perfiles where f_uuid=p_actor_uuid and f_activo and f_rol in ('administrator','inventory');
 if not found then raise exception 'Permiso de inventario requerido'; end if;
 select f_nombre into v_categoria from api.t_categorias_productos where f_uuid=p_uuid_categoria and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Categoría inválida'; end if;
 select f_nombre into v_fabricante from api.t_fabricantes_productos where f_uuid=p_uuid_fabricante and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Fabricante inválido'; end if;
 select f_nombre into v_principio from api.t_principios_activos where f_uuid=p_uuid_principio_activo and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Principio activo inválido'; end if;
 select f_nombre into v_unidad from api.t_unidades_medida where f_uuid=p_uuid_unidad_medida and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Unidad de medida inválida'; end if;
 select f_nombre into v_dummy from api.t_formas_farmaceuticas where f_uuid=p_uuid_forma_farmaceutica and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Forma farmacéutica inválida'; end if;
 select f_nombre into v_dummy from api.t_vias_administracion where f_uuid=p_uuid_via_administracion and f_idempresa=v_empresa and f_idsucursal=v_sucursal and f_app=v_app and f_activo; if not found then raise exception 'Vía de administración inválida'; end if;
 v_producto := api.fn_crear_producto_inventario_detallado(p_actor_uuid,p_codigo,p_nombre,p_presentacion,p_codigo_barras,v_principio,v_fabricante,v_categoria,v_unidad,p_registro_sanitario,p_requiere_receta,p_posiciones);
 update api.t_productos set f_uuid_categoria=p_uuid_categoria,f_uuid_fabricante=p_uuid_fabricante,f_uuid_principio_activo=p_uuid_principio_activo,f_uuid_unidad_medida=p_uuid_unidad_medida,f_uuid_forma_farmaceutica=p_uuid_forma_farmaceutica,f_uuid_via_administracion=p_uuid_via_administracion where f_uuid=v_producto;
 return v_producto;
end $$;

revoke all on function api.fn_crear_mantenimiento_inventario(uuid,text,text,text,text) from public,anon,authenticated;
revoke all on function api.fn_crear_producto_inventario_relacional(uuid,text,text,text,text,uuid,uuid,uuid,uuid,uuid,uuid,text,boolean,jsonb) from public,anon,authenticated;
grant execute on function api.fn_crear_mantenimiento_inventario(uuid,text,text,text,text) to service_role;
grant execute on function api.fn_crear_producto_inventario_relacional(uuid,text,text,text,text,uuid,uuid,uuid,uuid,uuid,uuid,text,boolean,jsonb) to service_role;

commit;
