begin;

create table if not exists api.t_revisores_documentos (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_perfil uuid not null references api.t_perfiles(f_uuid) on delete cascade,
 f_puede_revisar boolean not null default true, f_puede_crear_productos boolean not null default false,
 f_puede_contabilizar boolean not null default false, f_activo boolean not null default true,
 f_creado_en timestamptz not null default now(), f_actualizado_en timestamptz not null default now(),
 unique(f_id), unique(f_id_secuencia), unique(f_idempresa,f_idsucursal,f_app,f_uuid_perfil)
);

create table if not exists api.t_identidades_canales (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_perfil uuid references api.t_perfiles(f_uuid) on delete set null,
 f_canal text not null check(f_canal in ('whatsapp','web')), f_identificador_hash text not null,
 f_identificador_mascara text not null, f_verificado boolean not null default false, f_puede_enviar boolean not null default true,
 f_puede_decidir boolean not null default false, f_activo boolean not null default true,
 f_creado_en timestamptz not null default now(), f_actualizado_en timestamptz not null default now(),
 unique(f_id), unique(f_id_secuencia), unique(f_idempresa,f_idsucursal,f_app,f_canal,f_identificador_hash)
);

create table if not exists api.t_facturas_inventario (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_documento uuid not null references api.t_documentos(f_uuid), f_uuid_sucursal uuid not null references api.t_sucursales(f_uuid),
 f_uuid_identidad_canal uuid references api.t_identidades_canales(f_uuid), f_tipo_operacion text not null check(f_tipo_operacion in ('purchase','dispensation')),
 f_canal_origen text not null check(f_canal_origen in ('web','whatsapp')), f_referencia text, f_estado text not null default 'needs_review',
 f_total_renglones integer not null default 0, f_uuid_creado_por uuid references api.t_perfiles(f_uuid),
 f_uuid_aprobado_por uuid references api.t_perfiles(f_uuid), f_contabilizado_en timestamptz,
 f_creado_en timestamptz not null default now(), f_actualizado_en timestamptz not null default now(),
 unique(f_id), unique(f_id_secuencia), unique(f_uuid_documento)
);

create table if not exists api.t_renglones_factura (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_factura uuid not null references api.t_facturas_inventario(f_uuid) on delete cascade, f_numero integer not null,
 f_descripcion_original text not null, f_codigo_original text, f_codigo_barras_original text, f_cantidad numeric not null check(f_cantidad>0),
 f_unidad_original text, f_costo_unitario numeric, f_lote text, f_fecha_vencimiento date,
 f_uuid_producto uuid references api.t_productos(f_uuid), f_estado_conciliacion text not null,
 f_confianza numeric, f_candidatos jsonb not null default '[]'::jsonb, f_decision text,
 f_uuid_revisado_por uuid references api.t_perfiles(f_uuid), f_revisado_en timestamptz,
 f_creado_en timestamptz not null default now(), f_actualizado_en timestamptz not null default now(),
 unique(f_id), unique(f_id_secuencia), unique(f_uuid_factura,f_numero),
 check(f_estado_conciliacion in ('matched','ambiguous','product_missing','rejected','pending'))
);

create table if not exists api.t_revisiones_renglones (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_renglon uuid not null references api.t_renglones_factura(f_uuid) on delete cascade,
 f_uuid_revisor uuid not null references api.t_perfiles(f_uuid), f_accion text not null check(f_accion in ('link','reject','pending')),
 f_uuid_producto uuid references api.t_productos(f_uuid), f_motivo text, f_canal text not null check(f_canal in ('web','whatsapp')),
 f_creado_en timestamptz not null default now(), unique(f_id), unique(f_id_secuencia)
);

create table if not exists api.t_notificaciones_usuarios (
 f_id bigint generated by default as identity, f_id_secuencia bigint generated by default as identity,
 f_uuid uuid primary key default gen_random_uuid(), f_email_principal varchar not null default 'pendiente@local.dev',
 f_rnc_principal varchar not null default 'PENDIENTE', f_idempresa integer not null, f_idsucursal integer not null, f_app integer not null,
 f_uuid_destinatario uuid not null references api.t_perfiles(f_uuid), f_tipo text not null, f_titulo text not null, f_mensaje text not null,
 f_uuid_entidad uuid, f_canal_preferido text not null default 'web', f_estado text not null default 'pending',
 f_leido_en timestamptz, f_enviado_en timestamptz, f_creado_en timestamptz not null default now(),
 unique(f_id), unique(f_id_secuencia)
);

insert into api.t_revisores_documentos(f_uuid_perfil,f_puede_revisar,f_puede_crear_productos,f_puede_contabilizar,f_idempresa,f_idsucursal,f_app)
select p.f_uuid,true,true,true,p.f_idempresa,p.f_idsucursal,p.f_app from api.t_perfiles p
where p.f_rol='administrator' and p.f_activo
on conflict(f_idempresa,f_idsucursal,f_app,f_uuid_perfil) do update set f_puede_revisar=true,f_puede_crear_productos=true,f_puede_contabilizar=true,f_activo=true;

create index if not exists ix_revisores_documentos_tenant on api.t_revisores_documentos(f_idempresa,f_idsucursal,f_app,f_activo);
create index if not exists ix_identidades_canales_hash on api.t_identidades_canales(f_canal,f_identificador_hash,f_activo);
create index if not exists ix_facturas_inventario_tenant_estado on api.t_facturas_inventario(f_idempresa,f_idsucursal,f_app,f_estado);
create index if not exists ix_renglones_factura_estado on api.t_renglones_factura(f_idempresa,f_idsucursal,f_app,f_estado_conciliacion);
create index if not exists ix_notificaciones_destinatario on api.t_notificaciones_usuarios(f_uuid_destinatario,f_estado,f_creado_en desc);

alter table api.t_revisores_documentos enable row level security;
alter table api.t_identidades_canales enable row level security;
alter table api.t_facturas_inventario enable row level security;
alter table api.t_renglones_factura enable row level security;
alter table api.t_revisiones_renglones enable row level security;
alter table api.t_notificaciones_usuarios enable row level security;

alter table api.t_movimientos_inventario drop constraint if exists inventory_movements_movement_type_check;
alter table api.t_movimientos_inventario add constraint inventory_movements_movement_type_check
 check(f_tipo_movimiento in ('dispensation','reversal','reservation','release','adjustment','transfer_in','transfer_out','purchase_receipt'));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('invoice-private','invoice-private',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create or replace function api.fn_recibir_factura_inventario(
 p_actor_uuid uuid, p_canal text, p_identificador_canal text, p_tipo_operacion text,
 p_hash_contenido text, p_ruta_almacenamiento text, p_uuid_sucursal uuid, p_referencia text, p_renglones jsonb
) returns uuid language plpgsql security definer set search_path=api,public as $$
declare v_perfil api.t_perfiles%rowtype; v_identidad api.t_identidades_canales%rowtype; v_documento uuid; v_factura uuid; v_line jsonb; v_productos uuid[]; v_producto uuid; v_estado text; v_num integer:=0; v_total integer:=0; v_branch_id integer;
begin
 if p_canal not in ('web','whatsapp') or p_tipo_operacion not in ('purchase','dispensation') then raise exception 'Tipo de documento inválido'; end if;
 if p_hash_contenido !~ '^[a-fA-F0-9]{64}$' or p_ruta_almacenamiento not like 'private/%' then raise exception 'Imagen de factura inválida'; end if;
 if p_actor_uuid is not null then select * into v_perfil from api.t_perfiles where f_uuid=p_actor_uuid and f_activo;
 else
   select i.* into v_identidad from api.t_identidades_canales i where i.f_canal=p_canal and i.f_identificador_hash=encode(extensions.digest(regexp_replace(coalesce(p_identificador_canal,''),'\D','','g'),'sha256'),'hex') and i.f_verificado and i.f_puede_enviar and i.f_activo limit 1;
   if not found or v_identidad.f_uuid_perfil is null then raise exception 'Identidad de canal no autorizada'; end if;
   select * into v_perfil from api.t_perfiles where f_uuid=v_identidad.f_uuid_perfil and f_activo;
 end if;
 if v_perfil.f_uuid is null then raise exception 'Usuario no autorizado'; end if;
 select s.f_idsucursal into v_branch_id from api.t_sucursales s where s.f_uuid=p_uuid_sucursal and s.f_idempresa=v_perfil.f_idempresa and s.f_app=v_perfil.f_app and s.f_activo;
 if not found then raise exception 'Sucursal inválida'; end if;
 select f_uuid into v_documento from api.t_documentos where f_hash_contenido=p_hash_contenido and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app limit 1;
 if found then select f_uuid into v_factura from api.t_facturas_inventario where f_uuid_documento=v_documento; return v_factura; end if;
 insert into api.t_documentos(f_ambito_fuente,f_hash_contenido,f_tipo_documento,f_referencia,f_estado,f_ruta_almacenamiento,f_uuid_sucursal,f_uuid_creado_por,f_idempresa,f_idsucursal,f_app)
 values(p_canal,p_hash_contenido,'invoice',nullif(trim(p_referencia),''),'received',p_ruta_almacenamiento,p_uuid_sucursal,v_perfil.f_uuid,v_perfil.f_idempresa,v_branch_id,v_perfil.f_app) returning f_uuid into v_documento;
 insert into api.t_facturas_inventario(f_uuid_documento,f_uuid_sucursal,f_uuid_identidad_canal,f_tipo_operacion,f_canal_origen,f_referencia,f_uuid_creado_por,f_idempresa,f_idsucursal,f_app)
 values(v_documento,p_uuid_sucursal,case when v_identidad.f_idsucursal=v_branch_id then v_identidad.f_uuid else null end,p_tipo_operacion,p_canal,nullif(trim(p_referencia),''),v_perfil.f_uuid,v_perfil.f_idempresa,v_branch_id,v_perfil.f_app) returning f_uuid into v_factura;
 for v_line in select * from jsonb_array_elements(coalesce(p_renglones,'[]'::jsonb)) loop
   v_num:=v_num+1;
   if coalesce(trim(v_line->>'description'),'')='' or coalesce((v_line->>'quantity')::numeric,0)<=0 then raise exception 'Renglón de factura inválido'; end if;
   select array_agg(p.f_uuid order by p.f_uuid) into v_productos from api.t_productos p where p.f_idempresa=v_perfil.f_idempresa and p.f_app=v_perfil.f_app and p.f_activo and (
    (coalesce(v_line->>'code','')<>'' and upper(trim(p.f_codigo))=upper(trim(v_line->>'code'))) or
    (coalesce(v_line->>'barcode','')<>'' and p.f_codigo_barras=regexp_replace(v_line->>'barcode','\D','','g')) or
    (coalesce(v_line->>'code','')='' and coalesce(v_line->>'barcode','')='' and regexp_replace(upper(p.f_nombre),'[^A-Z0-9]','','g')=regexp_replace(upper(v_line->>'description'),'[^A-Z0-9]','','g'))
   );
   if coalesce(array_length(v_productos,1),0)=1 then v_producto:=v_productos[1]; v_estado:='matched';
   elsif coalesce(array_length(v_productos,1),0)>1 then v_producto:=null; v_estado:='ambiguous'; else v_producto:=null; v_estado:='product_missing'; end if;
   insert into api.t_renglones_factura(f_uuid_factura,f_numero,f_descripcion_original,f_codigo_original,f_codigo_barras_original,f_cantidad,f_unidad_original,f_costo_unitario,f_lote,f_fecha_vencimiento,f_uuid_producto,f_estado_conciliacion,f_candidatos,f_idempresa,f_idsucursal,f_app)
   values(v_factura,v_num,trim(v_line->>'description'),nullif(trim(v_line->>'code'),''),nullif(regexp_replace(v_line->>'barcode','\D','','g'),''),(v_line->>'quantity')::numeric,nullif(trim(v_line->>'unit'),''),nullif(v_line->>'unitCost','')::numeric,nullif(trim(v_line->>'lot'),''),nullif(v_line->>'expiryDate','')::date,v_producto,v_estado,to_jsonb(coalesce(v_productos,array[]::uuid[])),v_perfil.f_idempresa,v_branch_id,v_perfil.f_app);
   if v_estado<>'matched' then
    insert into api.t_notificaciones_usuarios(f_uuid_destinatario,f_tipo,f_titulo,f_mensaje,f_uuid_entidad,f_canal_preferido,f_idempresa,f_idsucursal,f_app)
    select r.f_uuid_perfil,'invoice_product_review','Producto de factura requiere revisión',trim(v_line->>'description'),v_factura,case when exists(select 1 from api.t_identidades_canales i where i.f_uuid_perfil=r.f_uuid_perfil and i.f_canal='whatsapp' and i.f_verificado and i.f_activo) then 'whatsapp' else 'web' end,r.f_idempresa,r.f_idsucursal,r.f_app
    from api.t_revisores_documentos r where r.f_idempresa=v_perfil.f_idempresa and r.f_app=v_perfil.f_app and r.f_puede_revisar and r.f_activo;
   end if;
 end loop;
 if v_num=0 then raise exception 'Renglones de factura requeridos'; end if;
 update api.t_facturas_inventario set f_total_renglones=v_num,f_estado=case when exists(select 1 from api.t_renglones_factura where f_uuid_factura=v_factura and f_estado_conciliacion<>'matched') then 'needs_review' else 'ready' end where f_uuid=v_factura;
 update api.t_documentos set f_estado='extracted' where f_uuid=v_documento;
 insert into api.t_eventos_auditoria(f_uuid_actor,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,f_metadatos_seguros,f_idempresa,f_idsucursal,f_app)
 values(v_perfil.f_uuid,'invoice.received','invoice',v_factura,v_factura,jsonb_build_object('channel',p_canal,'lines',v_num),v_perfil.f_idempresa,v_branch_id,v_perfil.f_app);
 return v_factura;
end $$;

create or replace function api.fn_decidir_renglon_factura(p_actor_uuid uuid,p_uuid_renglon uuid,p_accion text,p_uuid_producto uuid,p_motivo text,p_canal text)
returns void language plpgsql security definer set search_path=api,public as $$
declare v_r api.t_renglones_factura%rowtype; v_rev api.t_revisores_documentos%rowtype;
begin
 select l.* into v_r from api.t_renglones_factura l where l.f_uuid=p_uuid_renglon;
 select r.* into v_rev from api.t_revisores_documentos r where r.f_uuid_perfil=p_actor_uuid and r.f_idempresa=v_r.f_idempresa and r.f_app=v_r.f_app and r.f_activo and r.f_puede_revisar;
 if not found then raise exception 'Revisor de documentos requerido'; end if;
 if p_accion not in ('link','reject','pending') then raise exception 'Decisión inválida'; end if;
 if p_accion='link' and not exists(select 1 from api.t_productos p where p.f_uuid=p_uuid_producto and p.f_idempresa=v_r.f_idempresa and p.f_app=v_r.f_app and p.f_activo) then raise exception 'Producto inválido'; end if;
 update api.t_renglones_factura set f_uuid_producto=case when p_accion='link' then p_uuid_producto else null end,f_estado_conciliacion=case p_accion when 'link' then 'matched' when 'reject' then 'rejected' else 'pending' end,f_decision=p_accion,f_uuid_revisado_por=p_actor_uuid,f_revisado_en=now(),f_actualizado_en=now() where f_uuid=p_uuid_renglon;
 insert into api.t_revisiones_renglones(f_uuid_renglon,f_uuid_revisor,f_accion,f_uuid_producto,f_motivo,f_canal,f_idempresa,f_idsucursal,f_app) values(p_uuid_renglon,p_actor_uuid,p_accion,case when p_accion='link' then p_uuid_producto else null end,nullif(trim(p_motivo),''),p_canal,v_r.f_idempresa,v_r.f_idsucursal,v_r.f_app);
 update api.t_facturas_inventario f set f_estado=case when exists(select 1 from api.t_renglones_factura l where l.f_uuid_factura=f.f_uuid and l.f_estado_conciliacion in ('ambiguous','product_missing','pending')) then 'needs_review' else 'ready' end where f.f_uuid=v_r.f_uuid_factura;
end $$;

create or replace function api.fn_contabilizar_factura_inventario(p_actor_uuid uuid,p_uuid_factura uuid)
returns void language plpgsql security definer set search_path=api,public as $$
declare v_f api.t_facturas_inventario%rowtype; v_rev api.t_revisores_documentos%rowtype; v_l record; v_branch_id integer;
begin
 select * into v_f from api.t_facturas_inventario where f_uuid=p_uuid_factura for update;
 select * into v_rev from api.t_revisores_documentos where f_uuid_perfil=p_actor_uuid and f_idempresa=v_f.f_idempresa and f_app=v_f.f_app and f_activo and f_puede_contabilizar;
 if not found then raise exception 'Aprobador de inventario requerido'; end if;
 if v_f.f_estado='posted' then return; end if;
 if v_f.f_tipo_operacion='dispensation' then raise exception 'Dispensación requiere autorización vinculada'; end if;
 if exists(select 1 from api.t_renglones_factura where f_uuid_factura=p_uuid_factura and f_estado_conciliacion not in ('matched','rejected')) then raise exception 'Factura requiere revisión'; end if;
 select f_idsucursal into v_branch_id from api.t_sucursales where f_uuid=v_f.f_uuid_sucursal and f_idempresa=v_f.f_idempresa and f_app=v_f.f_app;
 for v_l in select * from api.t_renglones_factura where f_uuid_factura=p_uuid_factura and f_estado_conciliacion='matched' loop
  if coalesce(v_l.f_lote,'')='' or v_l.f_fecha_vencimiento is null then raise exception 'Lote y vencimiento requeridos'; end if;
  insert into api.t_posiciones_inventario(f_uuid_producto,f_uuid_sucursal,f_disponible,f_reservado,f_minimo_reorden,f_lote,f_fecha_vencimiento,f_costo,f_actualizado_en,f_fuente,f_idempresa,f_idsucursal,f_app)
  values(v_l.f_uuid_producto,v_f.f_uuid_sucursal,v_l.f_cantidad,0,0,v_l.f_lote,v_l.f_fecha_vencimiento,v_l.f_costo_unitario,now(),'invoice',v_f.f_idempresa,v_branch_id,v_f.f_app)
  on conflict(f_idempresa,f_idsucursal,f_app,f_uuid_producto,f_uuid_sucursal,f_lote) do update set f_disponible=api.t_posiciones_inventario.f_disponible+excluded.f_disponible,f_costo=coalesce(excluded.f_costo,api.t_posiciones_inventario.f_costo),f_fecha_vencimiento=excluded.f_fecha_vencimiento,f_actualizado_en=now(),f_fuente='invoice';
  insert into api.t_movimientos_inventario(f_uuid_producto,f_uuid_sucursal,f_tipo_movimiento,f_cantidad,f_uuid_aprobado_por,f_idempresa,f_idsucursal,f_app) values(v_l.f_uuid_producto,v_f.f_uuid_sucursal,'purchase_receipt',v_l.f_cantidad,p_actor_uuid,v_f.f_idempresa,v_branch_id,v_f.f_app);
 end loop;
 update api.t_facturas_inventario set f_estado='posted',f_uuid_aprobado_por=p_actor_uuid,f_contabilizado_en=now(),f_actualizado_en=now() where f_uuid=p_uuid_factura;
 update api.t_documentos set f_estado='posted' where f_uuid=v_f.f_uuid_documento;
 insert into api.t_eventos_auditoria(f_uuid_actor,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,f_metadatos_seguros,f_idempresa,f_idsucursal,f_app) values(p_actor_uuid,'invoice.posted','invoice',p_uuid_factura,p_uuid_factura,'{}',v_f.f_idempresa,v_branch_id,v_f.f_app);
end $$;

revoke all on api.t_revisores_documentos,api.t_identidades_canales,api.t_facturas_inventario,api.t_renglones_factura,api.t_revisiones_renglones,api.t_notificaciones_usuarios from public,anon,authenticated;
grant all on api.t_revisores_documentos,api.t_identidades_canales,api.t_facturas_inventario,api.t_renglones_factura,api.t_revisiones_renglones,api.t_notificaciones_usuarios to service_role;
revoke all on function api.fn_recibir_factura_inventario(uuid,text,text,text,text,text,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function api.fn_decidir_renglon_factura(uuid,uuid,text,uuid,text,text) from public,anon,authenticated;
revoke all on function api.fn_contabilizar_factura_inventario(uuid,uuid) from public,anon,authenticated;
grant execute on function api.fn_recibir_factura_inventario(uuid,text,text,text,text,text,uuid,text,jsonb) to service_role;
grant execute on function api.fn_decidir_renglon_factura(uuid,uuid,text,uuid,text,text) to service_role;
grant execute on function api.fn_contabilizar_factura_inventario(uuid,uuid) to service_role;
commit;
