-- Plan de seguimiento de uso continuo por ARS.
-- Las escrituras se realizan exclusivamente mediante funciones server-only.
create extension if not exists pgcrypto;
create schema if not exists api;

create table if not exists api.t_reglas_ars (
  f_id bigint generated by default as identity unique,
  f_id_secuencia bigint generated by default as identity unique,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null default 'sistema@procontra.local',
  f_rnc_principal varchar(20) not null default 'SISTEMA',
  f_idempresa integer not null default 0,
  f_idsucursal integer not null default 0,
  f_app integer not null default 0,
  f_codigo varchar(40) not null,
  f_nombre varchar(120) not null,
  f_cantidad_recetas smallint,
  f_modo varchar(20) not null check (f_modo in ('monthly','case_number')),
  f_activa boolean not null default true,
  f_creado_en timestamptz not null default now(),
  check ((f_modo='case_number' and f_cantidad_recetas is null) or (f_modo='monthly' and f_cantidad_recetas between 1 and 12))
);
create unique index if not exists ux_t_reglas_ars_tenant_codigo on api.t_reglas_ars(f_idempresa,f_app,f_codigo);
create index if not exists ix_t_reglas_ars_tenant on api.t_reglas_ars(f_idempresa,f_idsucursal,f_app);

insert into api.t_reglas_ars(f_codigo,f_nombre,f_cantidad_recetas,f_modo) values
('mapfre','MAPFRE Salud ARS',6,'monthly'),
('monumental','ARS Monumental',4,'monthly'),
('aps','ARS APS',3,'monthly'),
('humano','Humano Seguros',6,'monthly'),
('renacer','ARS Renacer SRL',3,'monthly'),
('futuro','ARS Futuro',3,'monthly'),
('universal','ARS Universal',6,'monthly'),
('asemap','ARS ASEMAP',3,'monthly'),
('metasalud','ARS Meta Salud',3,'monthly'),
('idoppril','IDOPPRIL',null,'case_number'),
('semma-pyp','ARS SEMMA PyP',6,'monthly'),
('reservas','ARS Reservas',3,'monthly'),
('gma','ARS GMA',3,'monthly'),
('yunen','ARS Yunen / Seguros Yunen',3,'monthly'),
('cmd','ARS-CMD (Colegio Médico Dominicano)',3,'monthly'),
('semma-70-30','ARS SEMMA 70/30',3,'monthly'),
('senasa','ARS SENASA',3,'monthly'),
('primera','ARS Primera',6,'monthly'),
('abel-gonzalez','ARS Abel González',3,'monthly')
on conflict (f_idempresa,f_app,f_codigo) do update set
  f_nombre=excluded.f_nombre,
  f_cantidad_recetas=excluded.f_cantidad_recetas,
  f_modo=excluded.f_modo,
  f_activa=true;

create table if not exists api.t_planes_seguimiento (
  f_id bigint generated by default as identity unique,
  f_id_secuencia bigint generated by default as identity unique,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null,
  f_rnc_principal varchar(20) not null,
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_paciente uuid not null references api.t_pacientes(f_uuid),
  f_uuid_regla_ars uuid not null references api.t_reglas_ars(f_uuid),
  f_medicamentos text not null,
  f_medico varchar(180),
  f_numero_caso varchar(100),
  f_fecha_primera_compra date not null,
  f_fecha_ultima_compra date not null,
  f_numero_receta_actual smallint not null default 1,
  f_proxima_compra date,
  f_fecha_contacto date,
  f_estado varchar(30) not null default 'active' check (f_estado in ('active','paused','completed','retired')),
  f_ultimo_resultado varchar(40),
  f_observaciones text,
  f_creado_por uuid,
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  check (length(trim(f_medicamentos)) between 2 and 2000)
);
create unique index if not exists ux_t_planes_seguimiento_tenant_paciente
  on api.t_planes_seguimiento(f_idempresa,f_app,f_uuid_paciente,f_uuid_regla_ars,f_fecha_primera_compra)
  where f_estado in ('active','paused');
create index if not exists ix_t_planes_seguimiento_tenant on api.t_planes_seguimiento(f_idempresa,f_idsucursal,f_app);
create index if not exists ix_t_planes_seguimiento_contacto on api.t_planes_seguimiento(f_idempresa,f_app,f_estado,f_fecha_contacto);

create table if not exists api.t_contactos_seguimiento (
  f_id bigint generated by default as identity unique,
  f_id_secuencia bigint generated by default as identity unique,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null,
  f_rnc_principal varchar(20) not null,
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_plan uuid not null references api.t_planes_seguimiento(f_uuid) on delete cascade,
  f_fecha_contacto timestamptz not null default now(),
  f_canal varchar(20) not null default 'call' check (f_canal in ('call','whatsapp','in_person')),
  f_resultado varchar(40) not null check (f_resultado in ('contesto','no_contesto','ya_tiene_receta','no_tiene_receta','tiene_cita_medica','esperando_autorizacion','comprara_efectivo','volver_a_llamar','enviar_a_casa','compro')),
  f_observaciones text,
  f_proxima_accion_en date,
  f_registrado_por uuid,
  f_creado_en timestamptz not null default now()
);
create index if not exists ix_t_contactos_seguimiento_tenant on api.t_contactos_seguimiento(f_idempresa,f_idsucursal,f_app);
create index if not exists ix_t_contactos_seguimiento_plan on api.t_contactos_seguimiento(f_uuid_plan,f_fecha_contacto desc);

alter table api.t_reglas_ars enable row level security;
alter table api.t_planes_seguimiento enable row level security;
alter table api.t_contactos_seguimiento enable row level security;

create or replace function api.fn_fecha_mensual(p_fecha date,p_meses integer)
returns date language sql immutable as $$
  select make_date(
    extract(year from (date_trunc('month',p_fecha)+(p_meses||' months')::interval))::integer,
    extract(month from (date_trunc('month',p_fecha)+(p_meses||' months')::interval))::integer,
    least(extract(day from p_fecha)::integer,extract(day from (date_trunc('month',p_fecha)+(p_meses||' months')::interval+interval '1 month - 1 day'))::integer)
  );
$$;

create or replace function api.fn_crear_plan_seguimiento(
  p_empresa integer,p_sucursal integer,p_app integer,p_email text,p_rnc text,p_usuario uuid,
  p_uuid_paciente uuid,p_codigo_ars text,p_fecha_primera_compra date,p_medicamentos text,
  p_medico text default null,p_numero_caso text default null,p_observaciones text default null
) returns uuid language plpgsql security definer set search_path=api,public as $$
declare v_regla api.t_reglas_ars%rowtype; v_uuid uuid; v_paciente record;
begin
  if p_fecha_primera_compra is null or p_fecha_primera_compra>current_date then raise exception 'Fecha de primera compra inválida'; end if;
  if length(trim(coalesce(p_medicamentos,'')))<2 then raise exception 'Medicamentos requeridos'; end if;
  select f_uuid into v_paciente from api.t_pacientes where f_uuid=p_uuid_paciente and f_idempresa=p_empresa and f_app=p_app and f_activo=true;
  if not found then raise exception 'Paciente no disponible'; end if;
  select * into v_regla from api.t_reglas_ars where f_codigo=p_codigo_ars and f_activa=true and f_idempresa=0 and f_app=0;
  if not found then raise exception 'ARS no configurada'; end if;
  if v_regla.f_modo='case_number' and length(trim(coalesce(p_numero_caso,'')))<2 then raise exception 'Número de caso requerido para IDOPPRIL'; end if;
  insert into api.t_planes_seguimiento(
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_paciente,f_uuid_regla_ars,
    f_medicamentos,f_medico,f_numero_caso,f_fecha_primera_compra,f_fecha_ultima_compra,
    f_proxima_compra,f_fecha_contacto,f_observaciones,f_creado_por
  ) values (
    p_email,p_rnc,p_empresa,p_sucursal,p_app,p_uuid_paciente,v_regla.f_uuid,
    trim(p_medicamentos),nullif(trim(coalesce(p_medico,'')),''),nullif(trim(coalesce(p_numero_caso,'')),''),
    p_fecha_primera_compra,p_fecha_primera_compra,
    case when v_regla.f_modo='monthly' then api.fn_fecha_mensual(p_fecha_primera_compra,1) end,
    case when v_regla.f_modo='monthly' then api.fn_fecha_mensual(p_fecha_primera_compra,1)-7 end,
    nullif(trim(coalesce(p_observaciones,'')),''),p_usuario
  ) returning f_uuid into v_uuid;
  return v_uuid;
end; $$;

create or replace function api.fn_registrar_resultado_seguimiento(
  p_empresa integer,p_app integer,p_uuid_plan uuid,p_resultado text,p_canal text,p_observaciones text,
  p_proxima_accion date,p_usuario uuid
) returns void language plpgsql security definer set search_path=api,public as $$
declare v_plan api.t_planes_seguimiento%rowtype; v_regla api.t_reglas_ars%rowtype; v_numero integer;
begin
  select * into v_plan from api.t_planes_seguimiento where f_uuid=p_uuid_plan and f_idempresa=p_empresa and f_app=p_app for update;
  if not found then raise exception 'Plan no disponible'; end if;
  if p_resultado not in ('contesto','no_contesto','ya_tiene_receta','no_tiene_receta','tiene_cita_medica','esperando_autorizacion','comprara_efectivo','volver_a_llamar','enviar_a_casa','compro') then raise exception 'Resultado inválido'; end if;
  select * into v_regla from api.t_reglas_ars where f_uuid=v_plan.f_uuid_regla_ars;
  insert into api.t_contactos_seguimiento(
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_plan,f_canal,f_resultado,
    f_observaciones,f_proxima_accion_en,f_registrado_por
  ) values (
    v_plan.f_email_principal,v_plan.f_rnc_principal,v_plan.f_idempresa,v_plan.f_idsucursal,v_plan.f_app,v_plan.f_uuid,
    coalesce(nullif(p_canal,''),'call'),p_resultado,nullif(trim(coalesce(p_observaciones,'')),''),p_proxima_accion,p_usuario
  );
  if p_resultado='compro' and v_regla.f_modo='monthly' then
    v_numero:=v_plan.f_numero_receta_actual+1;
    update api.t_planes_seguimiento set
      f_fecha_ultima_compra=current_date,f_numero_receta_actual=v_numero,
      f_estado=case when v_numero>=v_regla.f_cantidad_recetas then 'completed' else 'active' end,
      f_proxima_compra=case when v_numero>=v_regla.f_cantidad_recetas then null else api.fn_fecha_mensual(f_fecha_primera_compra,v_numero) end,
      f_fecha_contacto=case when v_numero>=v_regla.f_cantidad_recetas then null else api.fn_fecha_mensual(f_fecha_primera_compra,v_numero)-7 end,
      f_ultimo_resultado=p_resultado,f_actualizado_en=now()
    where f_uuid=p_uuid_plan;
  else
    update api.t_planes_seguimiento set f_ultimo_resultado=p_resultado,
      f_fecha_contacto=case when p_proxima_accion is not null then p_proxima_accion else f_fecha_contacto end,
      f_actualizado_en=now() where f_uuid=p_uuid_plan;
  end if;
end; $$;

create or replace function api.fn_consultar_planes_seguimiento(
  p_empresa integer,p_app integer,p_busqueda text default '',p_estado text default 'all',p_codigo_ars text default '',
  p_codigo_sucursal text default '',p_limite integer default 25,p_desplazamiento integer default 0
) returns table(
  f_uuid uuid,f_uuid_paciente uuid,f_nombre_completo text,f_telefono text,f_ars text,f_codigo_ars text,
  f_cantidad_recetas smallint,f_modo text,f_sucursal text,f_codigo_sucursal text,f_medicamentos text,f_medico text,
  f_numero_caso text,f_fecha_primera_compra date,f_fecha_ultima_compra date,f_numero_receta_actual smallint,
  f_proxima_compra date,f_fecha_contacto date,f_estado text,f_ultimo_resultado text,f_total_registros bigint
) language sql stable security definer set search_path=api,public as $$
  with filtrados as (
    select pl.*,pa.f_nombre_completo,pa.f_telefono,r.f_nombre as ars,r.f_codigo as codigo_ars,r.f_cantidad_recetas,r.f_modo,
      s.f_nombre as sucursal,s.f_codigo as codigo_sucursal
    from api.t_planes_seguimiento pl
    join api.t_pacientes pa on pa.f_uuid=pl.f_uuid_paciente and pa.f_idempresa=pl.f_idempresa and pa.f_app=pl.f_app
    join api.t_reglas_ars r on r.f_uuid=pl.f_uuid_regla_ars
    left join api.t_sucursales s on s.f_uuid=pa.f_uuid_sucursal_preferida and s.f_idempresa=pl.f_idempresa and s.f_app=pl.f_app
    where pl.f_idempresa=p_empresa and pl.f_app=p_app
      and (p_estado='all' or pl.f_estado=p_estado)
      and (p_codigo_ars='' or r.f_codigo=p_codigo_ars)
      and (p_codigo_sucursal='' or s.f_codigo=p_codigo_sucursal)
      and (trim(p_busqueda)='' or pa.f_nombre_completo ilike '%'||trim(p_busqueda)||'%' or pa.f_telefono ilike '%'||trim(p_busqueda)||'%' or pl.f_medicamentos ilike '%'||trim(p_busqueda)||'%')
  )
  select f_uuid,f_uuid_paciente,f_nombre_completo,f_telefono,ars,codigo_ars,f_cantidad_recetas,f_modo,sucursal,codigo_sucursal,
    f_medicamentos,f_medico,f_numero_caso,f_fecha_primera_compra,f_fecha_ultima_compra,f_numero_receta_actual,
    f_proxima_compra,f_fecha_contacto,f_estado,f_ultimo_resultado,count(*) over()
  from filtrados order by f_fecha_contacto nulls last,f_nombre_completo limit greatest(1,least(p_limite,100)) offset greatest(p_desplazamiento,0);
$$;

create or replace function api.fn_resumen_planes_seguimiento(p_empresa integer,p_app integer)
returns table(f_total bigint,f_contactar_hoy bigint,f_atrasados bigint,f_proximos_7_dias bigint,f_completados bigint)
language sql stable security definer set search_path=api,public as $$
  select count(*),count(*) filter(where f_estado='active' and f_fecha_contacto=current_date),
    count(*) filter(where f_estado='active' and f_fecha_contacto<current_date),
    count(*) filter(where f_estado='active' and f_fecha_contacto>current_date and f_fecha_contacto<=current_date+7),
    count(*) filter(where f_estado='completed')
  from api.t_planes_seguimiento where f_idempresa=p_empresa and f_app=p_app;
$$;

grant select on api.t_reglas_ars to service_role;
grant select,insert,update on api.t_planes_seguimiento to service_role;
grant select,insert on api.t_contactos_seguimiento to service_role;
grant execute on function api.fn_fecha_mensual(date,integer) to service_role;
grant execute on function api.fn_crear_plan_seguimiento(integer,integer,integer,text,text,uuid,uuid,text,date,text,text,text,text) to service_role;
grant execute on function api.fn_registrar_resultado_seguimiento(integer,integer,uuid,text,text,text,date,uuid) to service_role;
grant execute on function api.fn_consultar_planes_seguimiento(integer,integer,text,text,text,text,integer,integer) to service_role;
grant execute on function api.fn_resumen_planes_seguimiento(integer,integer) to service_role;
