-- Reservas operativas con asignación auditable por lote.
begin;

create table if not exists api.t_asignaciones_reserva (
  f_id bigint generated by default as identity,
  f_id_secuencia bigint generated by default as identity,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null default 'pendiente@local.dev',
  f_rnc_principal varchar(20) not null default 'PENDIENTE',
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_reserva uuid not null references api.t_reservas(f_uuid) on delete cascade,
  f_uuid_posicion uuid not null references api.t_posiciones_inventario(f_uuid),
  f_cantidad numeric not null check(f_cantidad>0),
  f_liberada_en timestamptz,
  f_creado_en timestamptz not null default now(),
  unique(f_id),
  unique(f_id_secuencia),
  unique(f_idempresa,f_idsucursal,f_app,f_uuid_reserva,f_uuid_posicion)
);

create index if not exists ix_t_asignaciones_reserva_tenant
  on api.t_asignaciones_reserva(f_idempresa,f_idsucursal,f_app,f_uuid_reserva);
alter table api.t_asignaciones_reserva enable row level security;

drop trigger if exists tr_campos_base on api.t_asignaciones_reserva;
create trigger tr_campos_base before insert on api.t_asignaciones_reserva
for each row execute function api.fn_completar_campos_base();

drop trigger if exists validar_asignacion_reserva_tenant on api.t_asignaciones_reserva;
create trigger validar_asignacion_reserva_tenant before insert or update on api.t_asignaciones_reserva
for each row execute function api.fn_validar_referencias_tenant(
  'f_uuid_reserva','api.t_reservas','true',
  'f_uuid_posicion','api.t_posiciones_inventario','true'
);

create or replace function api.fn_consultar_reservas(
  p_empresa integer,
  p_app integer,
  p_busqueda text default '',
  p_estado text default 'all',
  p_codigo_sucursal text default '',
  p_limite integer default 25,
  p_desplazamiento integer default 0
) returns table(
  f_uuid uuid,
  f_referencia text,
  f_uuid_paciente uuid,
  f_nombre_paciente text,
  f_telefono text,
  f_uuid_producto uuid,
  f_codigo_producto text,
  f_nombre_producto text,
  f_presentacion text,
  f_uuid_sucursal uuid,
  f_codigo_sucursal text,
  f_nombre_sucursal text,
  f_cantidad numeric,
  f_estado text,
  f_expira_en timestamptz,
  f_creado_en timestamptz,
  f_total_registros bigint
) language sql stable security definer set search_path=api,public as $$
  with base as (
    select r.f_uuid,r.f_referencia,r.f_uuid_paciente,pa.f_nombre_completo as f_nombre_paciente,
      pa.f_telefono,r.f_uuid_producto,p.f_codigo as f_codigo_producto,p.f_nombre as f_nombre_producto,
      p.f_presentacion,r.f_uuid_sucursal,s.f_codigo as f_codigo_sucursal,s.f_nombre as f_nombre_sucursal,
      r.f_cantidad,r.f_estado,r.f_expira_en,r.f_creado_en
    from api.t_reservas r
    join api.t_pacientes pa on pa.f_uuid=r.f_uuid_paciente and pa.f_idempresa=r.f_idempresa and pa.f_app=r.f_app
    join api.t_productos p on p.f_uuid=r.f_uuid_producto and p.f_idempresa=r.f_idempresa and p.f_app=r.f_app
    join api.t_sucursales s on s.f_uuid=r.f_uuid_sucursal and s.f_idempresa=r.f_idempresa and s.f_app=r.f_app
    where r.f_idempresa=p_empresa and r.f_app=p_app
      and (coalesce(p_estado,'all')='all' or r.f_estado=p_estado)
      and (trim(coalesce(p_codigo_sucursal,''))='' or s.f_codigo=trim(p_codigo_sucursal))
      and (trim(coalesce(p_busqueda,''))='' or pa.f_nombre_completo ilike '%'||trim(p_busqueda)||'%'
        or pa.f_telefono ilike '%'||trim(p_busqueda)||'%' or p.f_codigo ilike '%'||trim(p_busqueda)||'%'
        or p.f_nombre ilike '%'||trim(p_busqueda)||'%' or r.f_referencia ilike '%'||trim(p_busqueda)||'%')
  )
  select base.*,count(*) over() from base
  order by case when f_estado='confirmed' then 0 else 1 end,f_expira_en,f_creado_en desc
  limit greatest(1,least(coalesce(p_limite,25),100)) offset greatest(coalesce(p_desplazamiento,0),0);
$$;

create or replace function api.fn_resumen_reservas(p_empresa integer,p_app integer)
returns table(f_total bigint,f_activas bigint,f_listas bigint,f_vencen_hoy bigint,f_vencidas bigint)
language sql stable security definer set search_path=api,public as $$
  select count(*),
    count(*) filter(where f_estado='confirmed'),
    count(*) filter(where f_estado='confirmed'),
    count(*) filter(where f_estado='confirmed' and f_expira_en::date=current_date),
    count(*) filter(where f_estado='confirmed' and f_expira_en<now())
  from api.t_reservas where f_idempresa=p_empresa and f_app=p_app;
$$;

create or replace function api.fn_crear_reserva(
  p_actor_uuid uuid,
  p_uuid_paciente uuid,
  p_uuid_producto uuid,
  p_uuid_sucursal uuid,
  p_cantidad numeric,
  p_expira_en timestamptz,
  p_referencia text default null
) returns uuid language plpgsql security definer set search_path=api,public as $$
declare
  v_perfil api.t_perfiles%rowtype;
  v_sucursal api.t_sucursales%rowtype;
  v_reserva uuid;
  v_referencia text;
  v_faltante numeric:=p_cantidad;
  v_tomar numeric;
  v_posicion api.t_posiciones_inventario%rowtype;
begin
  if coalesce(p_cantidad,0)<=0 then raise exception 'Cantidad de reserva inválida'; end if;
  if p_expira_en is null or p_expira_en<=now() then raise exception 'Vencimiento de reserva inválido'; end if;
  select * into v_perfil from api.t_perfiles where f_uuid=p_actor_uuid and f_activo for update;
  if not found then raise exception 'Usuario no autorizado'; end if;
  select * into v_sucursal from api.t_sucursales where f_uuid=p_uuid_sucursal
    and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_activo;
  if not found then raise exception 'Sucursal inválida'; end if;
  if not exists(select 1 from api.t_membresias_sucursales m where m.f_uuid_perfil=p_actor_uuid
    and m.f_uuid_sucursal=p_uuid_sucursal and m.f_idempresa=v_perfil.f_idempresa and m.f_app=v_perfil.f_app)
    and v_perfil.f_rol<>'administrator' then raise exception 'Sucursal no autorizada'; end if;
  if not exists(select 1 from api.t_pacientes where f_uuid=p_uuid_paciente and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_activo)
    then raise exception 'Paciente inválido'; end if;
  if not exists(select 1 from api.t_productos where f_uuid=p_uuid_producto and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_activo)
    then raise exception 'Producto inválido'; end if;

  v_referencia:=coalesce(nullif(trim(p_referencia),''),'RES-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,12)));
  select f_uuid into v_reserva from api.t_reservas where f_idempresa=v_perfil.f_idempresa
    and f_idsucursal=v_sucursal.f_idsucursal and f_app=v_perfil.f_app and f_referencia=v_referencia;
  if found then return v_reserva; end if;

  if coalesce((select sum(f_disponible-f_reservado) from api.t_posiciones_inventario
    where f_idempresa=v_perfil.f_idempresa and f_idsucursal=v_sucursal.f_idsucursal and f_app=v_perfil.f_app
      and f_uuid_producto=p_uuid_producto and f_uuid_sucursal=p_uuid_sucursal and f_fecha_vencimiento>=current_date),0)<p_cantidad
    then raise exception 'Inventario disponible insuficiente'; end if;

  insert into api.t_reservas(f_referencia,f_uuid_paciente,f_uuid_producto,f_uuid_sucursal,f_cantidad,f_estado,f_expira_en,
    f_uuid_confirmado_por,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
  values(v_referencia,p_uuid_paciente,p_uuid_producto,p_uuid_sucursal,p_cantidad,'confirmed',p_expira_en,p_actor_uuid,
    v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_sucursal.f_idsucursal,v_perfil.f_app)
  returning f_uuid into v_reserva;

  for v_posicion in select * from api.t_posiciones_inventario
    where f_idempresa=v_perfil.f_idempresa and f_idsucursal=v_sucursal.f_idsucursal and f_app=v_perfil.f_app
      and f_uuid_producto=p_uuid_producto and f_uuid_sucursal=p_uuid_sucursal
      and f_fecha_vencimiento>=current_date and f_disponible-f_reservado>0
    order by f_fecha_vencimiento,f_actualizado_en nulls last for update
  loop
    exit when v_faltante<=0;
    v_tomar:=least(v_faltante,v_posicion.f_disponible-v_posicion.f_reservado);
    update api.t_posiciones_inventario set f_reservado=f_reservado+v_tomar,f_actualizado_en=now() where f_uuid=v_posicion.f_uuid;
    insert into api.t_asignaciones_reserva(f_uuid_reserva,f_uuid_posicion,f_cantidad,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
    values(v_reserva,v_posicion.f_uuid,v_tomar,v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_sucursal.f_idsucursal,v_perfil.f_app);
    v_faltante:=v_faltante-v_tomar;
  end loop;
  if v_faltante>0 then raise exception 'Inventario disponible cambió durante la reserva'; end if;

  insert into api.t_movimientos_inventario(f_uuid_producto,f_uuid_sucursal,f_tipo_movimiento,f_cantidad,f_uuid_aprobado_por,
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
  values(p_uuid_producto,p_uuid_sucursal,'reservation',p_cantidad,p_actor_uuid,v_perfil.f_email_principal,v_perfil.f_rnc_principal,
    v_perfil.f_idempresa,v_sucursal.f_idsucursal,v_perfil.f_app);
  insert into api.t_eventos_auditoria(f_uuid_actor,f_uuid_sucursal,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,
    f_metadatos_seguros,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
  values(p_actor_uuid,p_uuid_sucursal,'reservation.created','reservation',v_reserva,v_reserva,jsonb_build_object('quantity',p_cantidad),
    v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_sucursal.f_idsucursal,v_perfil.f_app);
  return v_reserva;
end $$;

create or replace function api.fn_cambiar_estado_reserva(
  p_actor_uuid uuid,p_uuid_reserva uuid,p_estado text,p_uuid_dispensacion uuid default null
) returns void language plpgsql security definer set search_path=api,public as $$
declare
  v_perfil api.t_perfiles%rowtype;
  v_reserva api.t_reservas%rowtype;
  v_asignacion record;
  v_libera boolean;
begin
  if p_estado not in ('collected','delivered','expired','cancelled') then raise exception 'Estado de reserva inválido'; end if;
  select * into v_perfil from api.t_perfiles where f_uuid=p_actor_uuid and f_activo;
  if not found then raise exception 'Usuario no autorizado'; end if;
  select * into v_reserva from api.t_reservas where f_uuid=p_uuid_reserva
    and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app for update;
  if not found then raise exception 'Reserva no encontrada'; end if;
  if v_reserva.f_estado in ('collected','delivered','expired','cancelled') then
    if v_reserva.f_estado=p_estado then return; end if;
    raise exception 'Reserva ya cerrada';
  end if;
  if p_estado in ('collected','delivered') and (p_uuid_dispensacion is null or not exists(select 1 from api.t_dispensaciones
    where f_uuid=p_uuid_dispensacion and f_idempresa=v_reserva.f_idempresa and f_idsucursal=v_reserva.f_idsucursal and f_app=v_reserva.f_app))
    then raise exception 'Dispensación válida requerida'; end if;
  v_libera:=p_estado in ('collected','delivered','expired','cancelled');
  if v_libera then
    for v_asignacion in select a.f_uuid,a.f_uuid_posicion,a.f_cantidad from api.t_asignaciones_reserva a
      where a.f_uuid_reserva=p_uuid_reserva and a.f_liberada_en is null for update
    loop
      update api.t_posiciones_inventario set f_reservado=greatest(0,f_reservado-v_asignacion.f_cantidad),f_actualizado_en=now()
        where f_uuid=v_asignacion.f_uuid_posicion;
      update api.t_asignaciones_reserva set f_liberada_en=now() where f_uuid=v_asignacion.f_uuid;
    end loop;
    insert into api.t_movimientos_inventario(f_uuid_dispensacion,f_uuid_producto,f_uuid_sucursal,f_tipo_movimiento,f_cantidad,f_uuid_aprobado_por,
      f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
    values(case when p_estado in ('collected','delivered') then p_uuid_dispensacion else null end,v_reserva.f_uuid_producto,v_reserva.f_uuid_sucursal,'release',
      -v_reserva.f_cantidad,p_actor_uuid,v_reserva.f_email_principal,v_reserva.f_rnc_principal,v_reserva.f_idempresa,v_reserva.f_idsucursal,v_reserva.f_app);
  end if;
  update api.t_reservas set f_estado=p_estado,f_uuid_dispensacion=case when p_estado in ('collected','delivered') then p_uuid_dispensacion else f_uuid_dispensacion end
    where f_uuid=p_uuid_reserva;
  insert into api.t_eventos_auditoria(f_uuid_actor,f_uuid_sucursal,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,
    f_metadatos_seguros,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app)
  values(p_actor_uuid,v_reserva.f_uuid_sucursal,'reservation.'||p_estado,'reservation',p_uuid_reserva,p_uuid_reserva,'{}',
    v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_reserva.f_idempresa,v_reserva.f_idsucursal,v_reserva.f_app);
end $$;

revoke all on api.t_asignaciones_reserva from public,anon,authenticated;
grant all on api.t_asignaciones_reserva to service_role;
revoke all on function api.fn_consultar_reservas(integer,integer,text,text,text,integer,integer) from public,anon,authenticated;
revoke all on function api.fn_resumen_reservas(integer,integer) from public,anon,authenticated;
revoke all on function api.fn_crear_reserva(uuid,uuid,uuid,uuid,numeric,timestamptz,text) from public,anon,authenticated;
revoke all on function api.fn_cambiar_estado_reserva(uuid,uuid,text,uuid) from public,anon,authenticated;
grant execute on function api.fn_consultar_reservas(integer,integer,text,text,text,integer,integer) to service_role;
grant execute on function api.fn_resumen_reservas(integer,integer) to service_role;
grant execute on function api.fn_crear_reserva(uuid,uuid,uuid,uuid,numeric,timestamptz,text) to service_role;
grant execute on function api.fn_cambiar_estado_reserva(uuid,uuid,text,uuid) to service_role;

notify pgrst,'reload schema';
commit;
