-- Registro de planes centrado en la receta, recordatorios a tres días y trazabilidad append-only.
begin;

alter table api.t_planes_seguimiento
  add column if not exists f_numero_receta varchar(100),
  add column if not exists f_fecha_receta date,
  add column if not exists f_canales_recordatorio text[] not null default array['call']::text[],
  add column if not exists f_dias_anticipacion_recordatorio smallint not null default 3;

alter table api.t_planes_seguimiento drop constraint if exists ck_t_planes_seguimiento_dias_recordatorio;
alter table api.t_planes_seguimiento add constraint ck_t_planes_seguimiento_dias_recordatorio
  check (f_dias_anticipacion_recordatorio = 3);
alter table api.t_planes_seguimiento drop constraint if exists ck_t_planes_seguimiento_canales_recordatorio;
alter table api.t_planes_seguimiento add constraint ck_t_planes_seguimiento_canales_recordatorio
  check (
    cardinality(f_canales_recordatorio) between 1 and 2
    and f_canales_recordatorio <@ array['call','whatsapp']::text[]
  );

update api.t_planes_seguimiento
set f_fecha_receta=coalesce(f_fecha_receta,f_fecha_primera_compra),
    f_dias_anticipacion_recordatorio=3,
    f_fecha_contacto=case when f_estado='active' and f_proxima_compra is not null
      then (f_proxima_compra-interval '3 days')::date else f_fecha_contacto end;

create table if not exists api.t_items_receta_seguimiento (
  f_id bigint generated by default as identity unique,
  f_id_secuencia bigint generated by default as identity unique,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null,
  f_rnc_principal varchar(20) not null,
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_plan uuid not null references api.t_planes_seguimiento(f_uuid),
  f_posicion smallint not null,
  f_medicamento varchar(300) not null,
  f_dosis varchar(300),
  f_cantidad numeric(12,3),
  f_creado_por uuid,
  f_creado_en timestamptz not null default now(),
  check (f_posicion between 1 and 100),
  check (length(trim(f_medicamento)) between 2 and 300),
  check (f_cantidad is null or (f_cantidad>0 and f_cantidad<=999999))
);
create unique index if not exists ux_t_items_receta_seguimiento_plan_posicion
  on api.t_items_receta_seguimiento(f_idempresa,f_app,f_uuid_plan,f_posicion);
create index if not exists ix_t_items_receta_seguimiento_tenant
  on api.t_items_receta_seguimiento(f_idempresa,f_idsucursal,f_app);
alter table api.t_items_receta_seguimiento enable row level security;

create or replace function api.fn_aplicar_anticipacion_recordatorio_plan()
returns trigger language plpgsql set search_path=api,public as $$
begin
  new.f_dias_anticipacion_recordatorio:=3;
  if new.f_proxima_compra is null then
    new.f_fecha_contacto:=null;
  elsif tg_op='INSERT' or new.f_proxima_compra is distinct from old.f_proxima_compra then
    new.f_fecha_contacto:=(new.f_proxima_compra-interval '3 days')::date;
  end if;
  return new;
end; $$;

drop trigger if exists tg_t_planes_seguimiento_anticipacion on api.t_planes_seguimiento;
create trigger tg_t_planes_seguimiento_anticipacion
before insert or update of f_proxima_compra on api.t_planes_seguimiento
for each row execute function api.fn_aplicar_anticipacion_recordatorio_plan();

create or replace function api.fn_bloquear_mutacion_contacto_seguimiento()
returns trigger language plpgsql set search_path=api,public as $$
begin
  raise exception 'Contactos de seguimiento son inmutables';
end; $$;

drop trigger if exists tg_t_contactos_seguimiento_append_only on api.t_contactos_seguimiento;
create trigger tg_t_contactos_seguimiento_append_only
before update or delete on api.t_contactos_seguimiento
for each row execute function api.fn_bloquear_mutacion_contacto_seguimiento();

create or replace function api.fn_bloquear_mutacion_item_receta_seguimiento()
returns trigger language plpgsql set search_path=api,public as $$
begin
  raise exception 'Renglones de receta son inmutables';
end; $$;

drop trigger if exists tg_t_items_receta_seguimiento_append_only on api.t_items_receta_seguimiento;
create trigger tg_t_items_receta_seguimiento_append_only
before update or delete on api.t_items_receta_seguimiento
for each row execute function api.fn_bloquear_mutacion_item_receta_seguimiento();

drop function if exists api.fn_crear_plan_seguimiento(integer,integer,integer,text,text,uuid,uuid,text,date,text,text,text,text,text,integer,integer,date,date,date);
create function api.fn_crear_plan_seguimiento(
  p_empresa integer,p_sucursal integer,p_app integer,p_email text,p_rnc text,p_usuario uuid,
  p_uuid_paciente uuid,p_codigo_ars text,p_fecha_primera_compra date,p_medicamentos text,
  p_numero_receta text,p_fecha_receta date,p_items jsonb,p_canales_recordatorio text[],
  p_medico text default null,p_numero_caso text default null,p_observaciones text default null,
  p_programacion_modo text default 'ars_rule',p_cantidad_recetas integer default null,
  p_numero_receta_actual integer default 1,p_fecha_ultima_compra date default null,
  p_proxima_compra date default null,p_fecha_contacto date default null
) returns uuid language plpgsql security definer set search_path=api,public as $$
declare
  v_regla api.t_reglas_ars%rowtype;
  v_uuid uuid;
  v_paciente record;
  v_manual boolean;
  v_item jsonb;
  v_posicion integer;
  v_resumen text;
  v_uuid_sucursal uuid;
  v_hoy date:=(current_timestamp at time zone 'America/Santo_Domingo')::date;
begin
  if p_fecha_primera_compra is null or p_fecha_primera_compra>v_hoy then raise exception 'Fecha de primera compra inválida'; end if;
  if length(trim(coalesce(p_numero_receta,'')))<1 then raise exception 'Número de receta requerido'; end if;
  if p_fecha_receta is null or p_fecha_receta>v_hoy then raise exception 'Fecha de receta inválida'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items) not between 1 and 100 then raise exception 'Renglones de receta requeridos'; end if;
  if coalesce(cardinality(p_canales_recordatorio),0) not between 1 and 2
     or not p_canales_recordatorio <@ array['call','whatsapp']::text[]
     or cardinality(p_canales_recordatorio)<>cardinality(array(select distinct unnest(p_canales_recordatorio))) then
    raise exception 'Canales de recordatorio inválidos';
  end if;

  v_posicion:=0;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_posicion:=v_posicion+1;
    if length(trim(coalesce(v_item->>'medicine','')))<2 then raise exception 'Renglones de receta inválidos'; end if;
    if v_item ? 'quantity' and v_item->>'quantity' is not null and
       ((v_item->>'quantity') !~ '^[0-9]+([.][0-9]+)?$' or (v_item->>'quantity')::numeric<=0 or (v_item->>'quantity')::numeric>999999) then
      raise exception 'Renglones de receta inválidos';
    end if;
  end loop;

  select string_agg(trim(item.value->>'medicine'),', ' order by item.ordinality)
  into v_resumen from jsonb_array_elements(p_items) with ordinality as item(value,ordinality);
  if length(v_resumen)>2000 then raise exception 'Medicamentos requeridos'; end if;

  select f_uuid into v_paciente from api.t_pacientes
  where f_uuid=p_uuid_paciente and f_idempresa=p_empresa and f_app=p_app and f_activo=true;
  if not found then raise exception 'Paciente no disponible'; end if;
  select * into v_regla from api.t_reglas_ars
  where f_codigo=p_codigo_ars and f_activa=true and f_idempresa=0 and f_app=0;
  if not found then raise exception 'ARS no configurada'; end if;
  if v_regla.f_modo='case_number' and length(trim(coalesce(p_numero_caso,'')))<2 then
    raise exception 'Número de caso requerido para IDOPPRIL';
  end if;

  v_manual:=v_regla.f_modo='monthly' and p_programacion_modo='manual';
  if v_manual and (
    coalesce(p_cantidad_recetas,0) not between 1 and 24 or
    coalesce(p_numero_receta_actual,0) not between 1 and p_cantidad_recetas or
    p_fecha_ultima_compra is null or p_fecha_ultima_compra<p_fecha_primera_compra or
    p_proxima_compra is null or p_proxima_compra<p_fecha_ultima_compra
  ) then raise exception 'Programación manual inválida'; end if;

  insert into api.t_planes_seguimiento(
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_paciente,f_uuid_regla_ars,
    f_medicamentos,f_numero_receta,f_fecha_receta,f_canales_recordatorio,f_dias_anticipacion_recordatorio,
    f_medico,f_numero_caso,f_fecha_primera_compra,f_fecha_ultima_compra,f_numero_receta_actual,
    f_proxima_compra,f_fecha_contacto,f_programacion_modo,f_cantidad_recetas_plan,f_observaciones,f_creado_por
  ) values (
    p_email,p_rnc,p_empresa,p_sucursal,p_app,p_uuid_paciente,v_regla.f_uuid,
    v_resumen,trim(p_numero_receta),p_fecha_receta,p_canales_recordatorio,3,
    nullif(trim(coalesce(p_medico,'')),''),nullif(trim(coalesce(p_numero_caso,'')),''),p_fecha_primera_compra,
    case when v_manual then p_fecha_ultima_compra else p_fecha_primera_compra end,
    case when v_manual then p_numero_receta_actual else 1 end,
    case when v_manual then p_proxima_compra when v_regla.f_modo='monthly' then api.fn_fecha_mensual(p_fecha_primera_compra,1) end,
    case when v_manual then (p_proxima_compra-interval '3 days')::date
         when v_regla.f_modo='monthly' then (api.fn_fecha_mensual(p_fecha_primera_compra,1)-interval '3 days')::date end,
    case when v_manual then 'manual' else 'ars_rule' end,case when v_manual then p_cantidad_recetas end,
    nullif(trim(coalesce(p_observaciones,'')),''),p_usuario
  ) returning f_uuid into v_uuid;

  insert into api.t_items_receta_seguimiento(
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_plan,f_posicion,
    f_medicamento,f_dosis,f_cantidad,f_creado_por
  )
  select p_email,p_rnc,p_empresa,p_sucursal,p_app,v_uuid,item.ordinality::smallint,
    trim(item.value->>'medicine'),nullif(trim(coalesce(item.value->>'dosage','')),''),
    case when item.value->>'quantity' is null then null else (item.value->>'quantity')::numeric end,p_usuario
  from jsonb_array_elements(p_items) with ordinality as item(value,ordinality);

  select f_uuid into v_uuid_sucursal from api.t_sucursales
  where f_idempresa=p_empresa and f_app=p_app and f_idsucursal=p_sucursal limit 1;
  insert into api.t_eventos_auditoria(
    f_uuid_actor,f_uuid_sucursal,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,
    f_metadatos_seguros,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app
  ) values (
    p_usuario,v_uuid_sucursal,'follow_up.plan_registered','follow_up_plan',v_uuid,v_uuid,
    jsonb_build_object('prescriptionNumber',trim(p_numero_receta),'prescriptionDate',p_fecha_receta,
      'itemCount',jsonb_array_length(p_items),'reminderChannels',to_jsonb(p_canales_recordatorio),'reminderLeadDays',3),
    p_email,p_rnc,p_empresa,p_sucursal,p_app
  );
  return v_uuid;
end; $$;

drop function if exists api.fn_consultar_planes_seguimiento(integer,integer,text,text,text,text,integer,integer);
create function api.fn_consultar_planes_seguimiento(
  p_empresa integer,p_app integer,p_busqueda text default '',p_estado text default 'all',p_codigo_ars text default '',
  p_codigo_sucursal text default '',p_limite integer default 25,p_desplazamiento integer default 0
) returns table(
  f_uuid uuid,f_uuid_paciente uuid,f_nombre_completo text,f_telefono text,f_ars text,f_codigo_ars text,
  f_cantidad_recetas smallint,f_modo text,f_sucursal text,f_codigo_sucursal text,f_medicamentos text,
  f_numero_receta text,f_fecha_receta date,f_canales_recordatorio text[],f_dias_anticipacion_recordatorio smallint,
  f_medico text,f_numero_caso text,f_fecha_primera_compra date,f_fecha_ultima_compra date,
  f_numero_receta_actual smallint,f_proxima_compra date,f_fecha_contacto date,f_estado text,
  f_ultimo_resultado text,f_total_registros bigint
) language sql stable security definer set search_path=api,public as $$
  with parametros as (
    select (current_timestamp at time zone 'America/Santo_Domingo')::date as hoy
  ), filtrados as (
    select pl.*,pa.f_nombre_completo,pa.f_telefono,r.f_nombre as ars,r.f_codigo as codigo_ars,
      coalesce(pl.f_cantidad_recetas_plan,r.f_cantidad_recetas)::smallint as cantidad_recetas,r.f_modo,
      s.f_nombre as sucursal,s.f_codigo as codigo_sucursal
    from api.t_planes_seguimiento pl
    cross join parametros x
    join api.t_pacientes pa on pa.f_uuid=pl.f_uuid_paciente and pa.f_idempresa=pl.f_idempresa and pa.f_app=pl.f_app
    join api.t_reglas_ars r on r.f_uuid=pl.f_uuid_regla_ars
    left join api.t_sucursales s on s.f_uuid=pa.f_uuid_sucursal_preferida and s.f_idempresa=pl.f_idempresa and s.f_app=pl.f_app
    where pl.f_idempresa=p_empresa and pl.f_app=p_app
      and case coalesce(p_estado,'all')
        when 'contact_today' then pl.f_estado='active' and pl.f_fecha_contacto=x.hoy
        when 'overdue' then pl.f_estado='active' and pl.f_fecha_contacto<x.hoy
        when 'next_3_days' then pl.f_estado='active' and pl.f_fecha_contacto>x.hoy and pl.f_fecha_contacto<=x.hoy+interval '3 days'
        when 'all' then true
        else pl.f_estado=p_estado
      end
      and (p_codigo_ars='' or r.f_codigo=p_codigo_ars)
      and (p_codigo_sucursal='' or s.f_codigo=p_codigo_sucursal)
      and (trim(p_busqueda)='' or pa.f_nombre_completo ilike '%'||trim(p_busqueda)||'%' or pa.f_telefono ilike '%'||trim(p_busqueda)||'%' or pl.f_medicamentos ilike '%'||trim(p_busqueda)||'%')
  )
  select f_uuid,f_uuid_paciente,f_nombre_completo,f_telefono,ars,codigo_ars,cantidad_recetas,f_modo,
    sucursal,codigo_sucursal,f_medicamentos,f_numero_receta,f_fecha_receta,f_canales_recordatorio,
    f_dias_anticipacion_recordatorio,f_medico,f_numero_caso,f_fecha_primera_compra,f_fecha_ultima_compra,
    f_numero_receta_actual,f_proxima_compra,f_fecha_contacto,f_estado,f_ultimo_resultado,count(*) over()
  from filtrados order by f_fecha_contacto nulls last,f_nombre_completo
  limit greatest(1,least(p_limite,100)) offset greatest(p_desplazamiento,0);
$$;

create or replace function api.fn_historial_plan_seguimiento(
  p_empresa integer,p_app integer,p_uuid_plan uuid
) returns table(
  f_uuid uuid,f_tipo text,f_ocurrido_en timestamptz,f_canal text,f_resultado text,
  f_observaciones text,f_uuid_actor uuid,f_metadatos jsonb
) language sql stable security definer set search_path=api,public as $$
  with plan as (
    select p.* from api.t_planes_seguimiento p
    where p.f_uuid=p_uuid_plan and p.f_idempresa=p_empresa and p.f_app=p_app
  ), historial(f_uuid,f_tipo,f_ocurrido_en,f_canal,f_resultado,f_observaciones,f_uuid_actor,f_metadatos) as (
    select p.f_uuid,'plan_registered'::text,p.f_creado_en,null::text,null::text,p.f_observaciones,
      p.f_creado_por,jsonb_build_object(
        'prescriptionNumber',p.f_numero_receta,
        'prescriptionDate',p.f_fecha_receta,
        'medicines',p.f_medicamentos,
        'reminderChannels',to_jsonb(p.f_canales_recordatorio),
        'reminderLeadDays',p.f_dias_anticipacion_recordatorio
      )
    from plan p
    union all
    select c.f_uuid,'contact'::text,c.f_fecha_contacto,c.f_canal,c.f_resultado,c.f_observaciones,
      c.f_registrado_por,jsonb_build_object('nextActionDate',c.f_proxima_accion_en)
    from api.t_contactos_seguimiento c
    join plan p on p.f_uuid=c.f_uuid_plan
    where c.f_idempresa=p_empresa and c.f_app=p_app
  )
  select * from historial order by f_ocurrido_en desc;
$$;

revoke all on api.t_items_receta_seguimiento from public,anon,authenticated;
grant select,insert on api.t_items_receta_seguimiento to service_role;
grant execute on function api.fn_consultar_planes_seguimiento(integer,integer,text,text,text,text,integer,integer) to service_role;
revoke all on function api.fn_historial_plan_seguimiento(integer,integer,uuid) from public,anon,authenticated;
grant execute on function api.fn_historial_plan_seguimiento(integer,integer,uuid) to service_role;
revoke all on function api.fn_crear_plan_seguimiento(integer,integer,integer,text,text,uuid,uuid,text,date,text,text,date,jsonb,text[],text,text,text,text,integer,integer,date,date,date) from public,anon,authenticated;
grant execute on function api.fn_crear_plan_seguimiento(integer,integer,integer,text,text,uuid,uuid,text,date,text,text,date,jsonb,text[],text,text,text,text,integer,integer,date,date,date) to service_role;

notify pgrst, 'reload schema';
commit;
