-- Documentos de autorización ARS vinculados a pacientes y continuidad.
begin;

alter table api.t_documentos drop constraint if exists documents_document_type_check;
alter table api.t_documentos add constraint documents_document_type_check
  check (f_tipo_documento in ('invoice','authorization','insurance_authorization','prescription','other'));

create table if not exists api.t_autorizaciones_seguros (
  f_id bigint generated by default as identity,
  f_id_secuencia bigint generated by default as identity,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar not null default 'pendiente@local.dev',
  f_rnc_principal varchar not null default 'PENDIENTE',
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_documento uuid not null references api.t_documentos(f_uuid),
  f_uuid_paciente uuid not null references api.t_pacientes(f_uuid),
  f_uuid_plan uuid not null references api.t_planes_seguimiento(f_uuid),
  f_uuid_regla_ars uuid not null references api.t_reglas_ars(f_uuid),
  f_uuid_sucursal uuid not null references api.t_sucursales(f_uuid),
  f_numero_autorizacion text not null,
  f_fecha_autorizacion date not null,
  f_prescriptor text,
  f_canal_origen text not null check (f_canal_origen in ('web','whatsapp')),
  f_estado text not null default 'registered' check (f_estado in ('needs_review','registered','rejected')),
  f_uuid_creado_por uuid not null references api.t_perfiles(f_uuid),
  f_creado_en timestamptz not null default now(),
  f_actualizado_en timestamptz not null default now(),
  unique(f_id),
  unique(f_id_secuencia),
  unique(f_uuid_documento),
  unique(f_idempresa,f_app,f_uuid_regla_ars,f_numero_autorizacion)
);

create table if not exists api.t_renglones_autorizacion (
  f_id bigint generated by default as identity,
  f_id_secuencia bigint generated by default as identity,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar not null default 'pendiente@local.dev',
  f_rnc_principal varchar not null default 'PENDIENTE',
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_autorizacion uuid not null references api.t_autorizaciones_seguros(f_uuid) on delete restrict,
  f_posicion smallint not null check (f_posicion between 1 and 100),
  f_descripcion_original text not null,
  f_cantidad numeric not null check (f_cantidad>0 and f_cantidad<=999999),
  f_uuid_producto uuid references api.t_productos(f_uuid),
  f_estado_conciliacion text not null check (f_estado_conciliacion in ('matched','ambiguous','product_missing')),
  f_candidatos jsonb not null default '[]'::jsonb,
  f_creado_en timestamptz not null default now(),
  unique(f_id),
  unique(f_id_secuencia),
  unique(f_uuid_autorizacion,f_posicion)
);

create index if not exists ix_t_autorizaciones_seguros_tenant
  on api.t_autorizaciones_seguros(f_idempresa,f_idsucursal,f_app,f_creado_en desc);
create index if not exists ix_t_autorizaciones_seguros_paciente
  on api.t_autorizaciones_seguros(f_idempresa,f_app,f_uuid_paciente);
create index if not exists ix_t_renglones_autorizacion_tenant
  on api.t_renglones_autorizacion(f_idempresa,f_idsucursal,f_app,f_estado_conciliacion);

alter table api.t_autorizaciones_seguros enable row level security;
alter table api.t_renglones_autorizacion enable row level security;

create or replace function api.fn_bloquear_mutacion_renglon_autorizacion()
returns trigger language plpgsql set search_path=api,public as $$
begin
  raise exception 'Renglones de autorización son inmutables';
end; $$;

drop trigger if exists tg_t_renglones_autorizacion_append_only on api.t_renglones_autorizacion;
create trigger tg_t_renglones_autorizacion_append_only
before update or delete on api.t_renglones_autorizacion
for each row execute function api.fn_bloquear_mutacion_renglon_autorizacion();

create or replace function api.fn_registrar_autorizacion_continuidad(
  p_actor_uuid uuid,
  p_canal text,
  p_hash_contenido text,
  p_ruta_almacenamiento text,
  p_uuid_sucursal uuid,
  p_codigo_ars text,
  p_nombre_paciente text,
  p_telefono text,
  p_identificacion text,
  p_carnet text,
  p_numero_autorizacion text,
  p_fecha_autorizacion date,
  p_prescriptor text,
  p_estado_autorizado boolean,
  p_uso_continuo boolean,
  p_consentimiento boolean,
  p_canales_recordatorio text[],
  p_medicamentos jsonb,
  p_clave_datos text
) returns jsonb language plpgsql security definer set search_path=api,public,extensions as $$
declare
  v_perfil api.t_perfiles%rowtype;
  v_regla api.t_reglas_ars%rowtype;
  v_uuid_sucursal uuid;
  v_idsucursal integer;
  v_documento uuid;
  v_autorizacion uuid;
  v_paciente uuid;
  v_plan uuid;
  v_identificacion text:=nullif(regexp_replace(coalesce(p_identificacion,''),'\D','','g'),'');
  v_carnet text:=nullif(regexp_replace(coalesce(p_carnet,''),'\D','','g'),'');
  v_telefono text:=regexp_replace(coalesce(p_telefono,''),'\D','','g');
  v_identificacion_hash text;
  v_carnet_hash text;
  v_item jsonb;
  v_posicion integer:=0;
  v_productos uuid[];
  v_producto uuid;
  v_estado text;
  v_resumen text;
  v_hoy date:=(current_timestamp at time zone 'America/Santo_Domingo')::date;
begin
  select * into v_perfil from api.t_perfiles where f_uuid=p_actor_uuid and f_activo;
  if not found or v_perfil.f_rol not in ('administrator','coordinator','attention') then
    raise exception 'Permiso de documentos requerido';
  end if;
  select f_uuid,f_idsucursal into v_uuid_sucursal,v_idsucursal
  from api.t_sucursales
  where f_uuid=p_uuid_sucursal and f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_activo;
  if not found then raise exception 'Sucursal inválida'; end if;
  select * into v_regla from api.t_reglas_ars
  where f_codigo=lower(trim(coalesce(p_codigo_ars,''))) and f_activa=true and f_idempresa=0 and f_app=0;
  if not found then raise exception 'ARS no configurada'; end if;

  if p_canal not in ('web','whatsapp') then raise exception 'Canal de documento inválido'; end if;
  if p_hash_contenido !~ '^[a-fA-F0-9]{64}$' or p_ruta_almacenamiento not like 'private/%' then
    raise exception 'Documento de autorización inválido';
  end if;
  if not coalesce(p_estado_autorizado,false) then raise exception 'Estado autorizado requerido'; end if;
  if not coalesce(p_uso_continuo,false) then raise exception 'Uso continuo requerido'; end if;
  if not coalesce(p_consentimiento,false) then raise exception 'Consentimiento de seguimiento requerido'; end if;
  if p_fecha_autorizacion is null or p_fecha_autorizacion>v_hoy then raise exception 'Fecha de autorización inválida'; end if;
  if length(trim(coalesce(p_nombre_paciente,''))) not between 3 and 240 then raise exception 'Nombre de paciente inválido'; end if;
  if v_telefono !~ '^[0-9]{10,15}$' then raise exception 'Teléfono de paciente inválido'; end if;
  if v_identificacion is not null and v_identificacion !~ '^[0-9]{11}$' then raise exception 'Cédula de paciente inválida'; end if;
  if v_carnet is not null and v_carnet !~ '^[0-9]{8,12}$' then raise exception 'Carnet de paciente inválido'; end if;
  if length(trim(coalesce(p_numero_autorizacion,''))) not between 2 and 120 then raise exception 'Número de autorización requerido'; end if;
  if jsonb_typeof(p_medicamentos)<>'array' or jsonb_array_length(p_medicamentos) not between 1 and 100 then
    raise exception 'Medicamentos autorizados inválidos';
  end if;
  if coalesce(cardinality(p_canales_recordatorio),0) not between 1 and 2
     or not p_canales_recordatorio <@ array['call','whatsapp']::text[]
     or cardinality(p_canales_recordatorio)<>cardinality(array(select distinct unnest(p_canales_recordatorio))) then
    raise exception 'Canales de recordatorio inválidos';
  end if;
  if length(coalesce(p_clave_datos,''))<32 then raise exception 'Configuración de seguridad no disponible'; end if;

  select a.f_uuid,a.f_uuid_paciente,a.f_uuid_plan into v_autorizacion,v_paciente,v_plan
  from api.t_documentos d
  join api.t_autorizaciones_seguros a on a.f_uuid_documento=d.f_uuid
  where d.f_hash_contenido=lower(p_hash_contenido)
    and d.f_idempresa=v_perfil.f_idempresa and d.f_app=v_perfil.f_app
  limit 1;
  if found then
    return jsonb_build_object('authorizationId',v_autorizacion,'patientId',v_paciente,'planId',v_plan,'created',false);
  end if;

  select a.f_uuid,a.f_uuid_paciente,a.f_uuid_plan into v_autorizacion,v_paciente,v_plan
  from api.t_autorizaciones_seguros a
  where a.f_idempresa=v_perfil.f_idempresa and a.f_app=v_perfil.f_app
    and a.f_uuid_regla_ars=v_regla.f_uuid
    and upper(trim(a.f_numero_autorizacion))=upper(trim(p_numero_autorizacion))
  limit 1;
  if found then
    return jsonb_build_object('authorizationId',v_autorizacion,'patientId',v_paciente,'planId',v_plan,'created',false);
  end if;

  v_identificacion_hash:=case when v_identificacion is null then null else encode(extensions.hmac(v_identificacion,p_clave_datos,'sha256'),'hex') end;
  v_carnet_hash:=case when v_carnet is null then null else encode(extensions.hmac(v_carnet,p_clave_datos,'sha256'),'hex') end;

  if v_identificacion_hash is not null then
    select f_uuid into v_paciente from api.t_pacientes
    where f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_identificacion_hash=v_identificacion_hash and f_activo limit 1;
  end if;
  if v_paciente is null and v_carnet_hash is not null then
    select f_uuid into v_paciente from api.t_pacientes
    where f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_nss_hash=v_carnet_hash and f_activo limit 1;
  end if;
  if v_paciente is null then
    select f_uuid into v_paciente from api.t_pacientes
    where f_idempresa=v_perfil.f_idempresa and f_app=v_perfil.f_app and f_activo
      and regexp_replace(f_telefono,'\D','','g')=v_telefono
      and regexp_replace(upper(f_nombre_completo),'\s+',' ','g')=regexp_replace(upper(trim(p_nombre_paciente)),'\s+',' ','g')
    limit 1;
  end if;
  if v_paciente is null then
    select api.fn_crear_paciente(
      p_actor_uuid=>p_actor_uuid,p_codigo=>null,p_nombre=>p_nombre_paciente,p_telefono=>v_telefono,
      p_aseguradora=>v_regla.f_nombre,p_uuid_sucursal=>v_uuid_sucursal,p_consentimiento=>true,
      p_identificacion=>v_identificacion,p_nss=>v_carnet,p_fecha_nacimiento=>null,
      p_telefono_verificado=>p_canal='whatsapp',p_estado_seguimiento=>'green',
      p_canal_contacto=>case when 'whatsapp'=any(p_canales_recordatorio) then 'whatsapp' else 'call' end,
      p_clave_datos=>p_clave_datos
    ) into v_paciente;
  elsif not exists(
    select 1 from api.t_consentimientos c where c.f_uuid_paciente=v_paciente
      and c.f_idempresa=v_perfil.f_idempresa and c.f_app=v_perfil.f_app and c.f_estado='active'
  ) then
    insert into api.t_consentimientos(
      f_uuid_paciente,f_canal,f_propositos,f_estado,f_version_politica,f_otorgado_en,f_uuid_actor,
      f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app
    ) values(
      v_paciente,case when 'whatsapp'=any(p_canales_recordatorio) then 'whatsapp' else 'call' end,
      array['continuity','reminders'],'active','2026-01',now(),p_actor_uuid,
      v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_idsucursal,v_perfil.f_app
    );
  end if;

  select string_agg(trim(item.value->>'medicine'),', ' order by item.ordinality)
  into v_resumen from jsonb_array_elements(p_medicamentos) with ordinality as item(value,ordinality);

  select pl.f_uuid into v_plan
  from api.t_planes_seguimiento pl
  where pl.f_idempresa=v_perfil.f_idempresa and pl.f_app=v_perfil.f_app
    and pl.f_uuid_paciente=v_paciente and pl.f_uuid_regla_ars=v_regla.f_uuid
    and upper(trim(coalesce(pl.f_numero_caso,'')))=upper(trim(p_numero_autorizacion))
    and pl.f_fecha_receta=p_fecha_autorizacion
  limit 1;
  if v_plan is null then
    select api.fn_crear_plan_seguimiento(
      p_empresa=>v_perfil.f_idempresa,p_sucursal=>v_idsucursal,p_app=>v_perfil.f_app,
      p_email=>v_perfil.f_email_principal,p_rnc=>v_perfil.f_rnc_principal,p_usuario=>p_actor_uuid,
      p_uuid_paciente=>v_paciente,p_codigo_ars=>v_regla.f_codigo,
      p_fecha_primera_compra=>p_fecha_autorizacion,p_medicamentos=>v_resumen,
      p_numero_receta=>null,p_fecha_receta=>p_fecha_autorizacion,p_items=>p_medicamentos,
      p_canales_recordatorio=>p_canales_recordatorio,p_medico=>p_prescriptor,
      p_numero_caso=>trim(p_numero_autorizacion),
      p_observaciones=>'Registrado desde autorización de seguro; la fecha base corresponde a la autorización y no prueba una dispensación.'
    ) into v_plan;
  end if;

  insert into api.t_documentos(
    f_ambito_fuente,f_hash_contenido,f_tipo_documento,f_referencia,f_estado,f_ruta_almacenamiento,
    f_uuid_paciente,f_uuid_sucursal,f_uuid_creado_por,f_email_principal,f_rnc_principal,
    f_idempresa,f_idsucursal,f_app
  ) values(
    p_canal,lower(p_hash_contenido),'insurance_authorization',trim(p_numero_autorizacion),'linked',p_ruta_almacenamiento,
    v_paciente,v_uuid_sucursal,p_actor_uuid,v_perfil.f_email_principal,v_perfil.f_rnc_principal,
    v_perfil.f_idempresa,v_idsucursal,v_perfil.f_app
  ) returning f_uuid into v_documento;

  insert into api.t_autorizaciones_seguros(
    f_uuid_documento,f_uuid_paciente,f_uuid_plan,f_uuid_regla_ars,f_uuid_sucursal,
    f_numero_autorizacion,f_fecha_autorizacion,f_prescriptor,f_canal_origen,f_estado,f_uuid_creado_por,
    f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app
  ) values(
    v_documento,v_paciente,v_plan,v_regla.f_uuid,v_uuid_sucursal,trim(p_numero_autorizacion),p_fecha_autorizacion,
    nullif(trim(coalesce(p_prescriptor,'')),''),p_canal,'registered',p_actor_uuid,
    v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_idsucursal,v_perfil.f_app
  ) returning f_uuid into v_autorizacion;

  for v_item in select value from jsonb_array_elements(p_medicamentos) loop
    v_posicion:=v_posicion+1;
    if length(trim(coalesce(v_item->>'medicine','')))<2
       or coalesce(v_item->>'quantity','') !~ '^[0-9]+([.][0-9]+)?$'
       or (v_item->>'quantity')::numeric<=0 or (v_item->>'quantity')::numeric>999999 then
      raise exception 'Medicamentos autorizados inválidos';
    end if;
    select array_agg(p.f_uuid order by p.f_uuid) into v_productos
    from api.t_productos p
    where p.f_idempresa=v_perfil.f_idempresa and p.f_app=v_perfil.f_app and p.f_activo
      and regexp_replace(upper(p.f_nombre),'[^A-Z0-9]','','g')=regexp_replace(upper(v_item->>'medicine'),'[^A-Z0-9]','','g');
    if coalesce(array_length(v_productos,1),0)=1 then v_producto:=v_productos[1]; v_estado:='matched';
    elsif coalesce(array_length(v_productos,1),0)>1 then v_producto:=null; v_estado:='ambiguous';
    else v_producto:=null; v_estado:='product_missing'; end if;
    insert into api.t_renglones_autorizacion(
      f_uuid_autorizacion,f_posicion,f_descripcion_original,f_cantidad,f_uuid_producto,f_estado_conciliacion,f_candidatos,
      f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app
    ) values(
      v_autorizacion,v_posicion,trim(v_item->>'medicine'),(v_item->>'quantity')::numeric,v_producto,v_estado,
      to_jsonb(coalesce(v_productos,array[]::uuid[])),v_perfil.f_email_principal,v_perfil.f_rnc_principal,
      v_perfil.f_idempresa,v_idsucursal,v_perfil.f_app
    );
  end loop;

  insert into api.t_eventos_auditoria(
    f_uuid_actor,f_uuid_sucursal,f_tipo_evento,f_tipo_entidad,f_uuid_entidad,f_uuid_correlacion,
    f_metadatos_seguros,f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app
  ) values(
    p_actor_uuid,v_uuid_sucursal,'insurance_authorization.registered','insurance_authorization',v_autorizacion,v_plan,
    jsonb_build_object('documentId',v_documento,'patientId',v_paciente,'planId',v_plan,'itemCount',v_posicion,'channel',p_canal),
    v_perfil.f_email_principal,v_perfil.f_rnc_principal,v_perfil.f_idempresa,v_idsucursal,v_perfil.f_app
  );

  return jsonb_build_object('authorizationId',v_autorizacion,'patientId',v_paciente,'planId',v_plan,'created',true);
end; $$;

revoke all on api.t_autorizaciones_seguros,api.t_renglones_autorizacion from public,anon,authenticated;
grant select,insert,update on api.t_autorizaciones_seguros to service_role;
grant select,insert on api.t_renglones_autorizacion to service_role;
revoke all on function api.fn_registrar_autorizacion_continuidad(uuid,text,text,text,uuid,text,text,text,text,text,text,date,text,boolean,boolean,boolean,text[],jsonb,text) from public,anon,authenticated;
grant execute on function api.fn_registrar_autorizacion_continuidad(uuid,text,text,text,uuid,text,text,text,text,text,text,date,text,boolean,boolean,boolean,text[],jsonb,text) to service_role;

notify pgrst, 'reload schema';
commit;
