begin;

create table if not exists api.t_historial_identificadores_paciente (
  f_id bigint generated by default as identity unique,
  f_id_secuencia bigint generated by default as identity unique,
  f_uuid uuid primary key default gen_random_uuid(),
  f_email_principal varchar(180) not null,
  f_rnc_principal varchar(20) not null,
  f_idempresa integer not null,
  f_idsucursal integer not null,
  f_app integer not null,
  f_uuid_paciente uuid not null references api.t_pacientes(f_uuid),
  f_tipo varchar(24) not null check (f_tipo in ('cedula','poliza')),
  f_valor_cifrado text not null,
  f_valor_hash text not null,
  f_valor_mascara text not null,
  f_uuid_actor uuid not null,
  f_creado_en timestamptz not null default now()
);

create index if not exists ix_t_historial_identificadores_paciente_tenant
  on api.t_historial_identificadores_paciente(f_idempresa,f_app,f_uuid_paciente,f_creado_en desc);

drop function if exists api.fn_consultar_identificadores_paciente(uuid,uuid,text);
create function api.fn_consultar_identificadores_paciente(
  p_actor_uuid uuid,
  p_paciente_uuid uuid,
  p_clave_datos text
) returns table(
  f_identificacion text,
  f_poliza text,
  f_identificacion_mascara text,
  f_poliza_mascara text
) language plpgsql stable security definer set search_path=api,public,extensions as $$
declare
  v_empresa integer;
  v_app integer;
  v_rol text;
begin
  select f_idempresa,f_app,f_rol into v_empresa,v_app,v_rol
  from api.t_perfiles where f_uuid=p_actor_uuid and f_activo;
  if v_empresa is null or v_rol not in ('administrator','coordinator','attention') then
    raise exception 'Permiso de pacientes requerido';
  end if;
  if length(coalesce(p_clave_datos,''))<32 then
    raise exception 'Configuración de seguridad no disponible';
  end if;

  return query
  select
    case when p.f_identificacion_cifrada is null then ''
      else extensions.pgp_sym_decrypt(decode(p.f_identificacion_cifrada,'base64'),p_clave_datos)::text end,
    case when p.f_nss_cifrado is null then ''
      else extensions.pgp_sym_decrypt(decode(p.f_nss_cifrado,'base64'),p_clave_datos)::text end,
    coalesce(p.f_identificacion_mascara,''),
    coalesce(p.f_nss_mascara,'')
  from api.t_pacientes p
  where p.f_uuid=p_paciente_uuid and p.f_idempresa=v_empresa and p.f_app=v_app;
end $$;

create or replace function api.fn_actualizar_paciente(
  p_actor_uuid uuid,
  p_paciente_uuid uuid,
  p_nombre text,
  p_telefono text,
  p_aseguradora text,
  p_uuid_sucursal uuid,
  p_identificacion text,
  p_nss text,
  p_fecha_nacimiento date,
  p_telefono_verificado boolean,
  p_estado_seguimiento text,
  p_canal_contacto text,
  p_activo boolean,
  p_clave_datos text
) returns uuid language plpgsql security definer set search_path=api,public,extensions as $$
declare
  v_empresa integer;
  v_sucursal_paciente integer;
  v_idsucursal_actual integer;
  v_app integer;
  v_rol text;
  v_email varchar(180);
  v_rnc varchar(20);
  v_identificacion text:=nullif(regexp_replace(coalesce(p_identificacion,''),'\D','','g'),'');
  v_nss text:=nullif(regexp_replace(coalesce(p_nss,''),'\D','','g'),'');
  v_identificacion_hash text;
  v_nss_hash text;
  v_identificacion_cifrada_actual text;
  v_identificacion_hash_actual text;
  v_identificacion_mascara_actual text;
  v_nss_cifrado_actual text;
  v_nss_hash_actual text;
  v_nss_mascara_actual text;
begin
  select f_idempresa,f_app,f_rol,f_email_principal,f_rnc_principal
    into v_empresa,v_app,v_rol,v_email,v_rnc
  from api.t_perfiles where f_uuid=p_actor_uuid and f_activo;
  if v_empresa is null or v_rol not in ('administrator','coordinator','attention') then
    raise exception 'Permiso de pacientes requerido';
  end if;

  select p.f_idsucursal,p.f_identificacion_cifrada,p.f_identificacion_hash,p.f_identificacion_mascara,
    p.f_nss_cifrado,p.f_nss_hash,p.f_nss_mascara
    into v_idsucursal_actual,v_identificacion_cifrada_actual,v_identificacion_hash_actual,v_identificacion_mascara_actual,
      v_nss_cifrado_actual,v_nss_hash_actual,v_nss_mascara_actual
  from api.t_pacientes p
  where p.f_uuid=p_paciente_uuid and p.f_idempresa=v_empresa and p.f_app=v_app;
  if not found then raise exception 'Paciente no encontrado'; end if;

  select f_idsucursal into v_sucursal_paciente from api.t_sucursales
  where f_uuid=p_uuid_sucursal and f_idempresa=v_empresa and f_app=v_app and f_activo;
  if v_sucursal_paciente is null then raise exception 'Sucursal de paciente inválida'; end if;
  if length(trim(coalesce(p_nombre,'')))<3 or length(trim(p_nombre))>240 then raise exception 'Nombre de paciente inválido'; end if;
  if trim(coalesce(p_telefono,'')) !~ '^[0-9]{10}$' then raise exception 'Teléfono de paciente inválido'; end if;
  if v_identificacion is not null and v_identificacion !~ '^[0-9]{11}$' then raise exception 'Cédula de paciente inválida'; end if;
  if v_nss is not null and v_nss !~ '^[0-9]{8,12}$' then raise exception 'NSS de paciente inválido'; end if;
  if p_fecha_nacimiento is not null and (p_fecha_nacimiento<date '1900-01-01' or p_fecha_nacimiento>current_date) then raise exception 'Fecha de nacimiento inválida'; end if;
  if coalesce(p_estado_seguimiento,'') not in ('green','yellow','red','clinical') then raise exception 'Estado de seguimiento inválido'; end if;
  if coalesce(p_canal_contacto,'') not in ('whatsapp','call') then raise exception 'Canal de contacto inválido'; end if;
  if length(coalesce(p_clave_datos,''))<32 then raise exception 'Configuración de seguridad no disponible'; end if;

  v_identificacion_hash:=case when v_identificacion is null then null else encode(extensions.hmac(v_identificacion,p_clave_datos,'sha256'),'hex') end;
  v_nss_hash:=case when v_nss is null then null else encode(extensions.hmac(v_nss,p_clave_datos,'sha256'),'hex') end;
  if v_identificacion_hash is not null and exists(select 1 from api.t_pacientes where f_idempresa=v_empresa and f_app=v_app and f_identificacion_hash=v_identificacion_hash and f_uuid<>p_paciente_uuid) then raise exception 'Cédula de paciente ya registrada'; end if;
  if v_nss_hash is not null and exists(select 1 from api.t_pacientes where f_idempresa=v_empresa and f_app=v_app and f_nss_hash=v_nss_hash and f_uuid<>p_paciente_uuid) then raise exception 'NSS de paciente ya registrado'; end if;

  if v_identificacion_hash is not null
    and v_identificacion_hash is distinct from v_identificacion_hash_actual
    and v_identificacion_cifrada_actual is not null then
    insert into api.t_historial_identificadores_paciente(
      f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_paciente,
      f_tipo,f_valor_cifrado,f_valor_hash,f_valor_mascara,f_uuid_actor
    ) values(
      v_email,v_rnc,v_empresa,v_idsucursal_actual,v_app,p_paciente_uuid,
      'cedula',v_identificacion_cifrada_actual,v_identificacion_hash_actual,v_identificacion_mascara_actual,p_actor_uuid
    );
  end if;

  if v_nss_hash is not null
    and v_nss_hash is distinct from v_nss_hash_actual
    and v_nss_cifrado_actual is not null then
    insert into api.t_historial_identificadores_paciente(
      f_email_principal,f_rnc_principal,f_idempresa,f_idsucursal,f_app,f_uuid_paciente,
      f_tipo,f_valor_cifrado,f_valor_hash,f_valor_mascara,f_uuid_actor
    ) values(
      v_email,v_rnc,v_empresa,v_idsucursal_actual,v_app,p_paciente_uuid,
      'poliza',v_nss_cifrado_actual,v_nss_hash_actual,v_nss_mascara_actual,p_actor_uuid
    );
  end if;

  update api.t_pacientes set
    f_nombre_completo=trim(regexp_replace(p_nombre,'\s+',' ','g')),
    f_telefono=p_telefono,
    f_aseguradora=nullif(trim(coalesce(p_aseguradora,'')),''),
    f_uuid_sucursal_preferida=p_uuid_sucursal,
    f_idsucursal=v_sucursal_paciente,
    f_identificacion_cifrada=case when v_identificacion is null then f_identificacion_cifrada else encode(extensions.pgp_sym_encrypt(v_identificacion,p_clave_datos,'cipher-algo=aes256'),'base64') end,
    f_identificacion_hash=case when v_identificacion is null then f_identificacion_hash else v_identificacion_hash end,
    f_identificacion_mascara=case when v_identificacion is null then f_identificacion_mascara else '***-*******-'||right(v_identificacion,1) end,
    f_nss_cifrado=case when v_nss is null then f_nss_cifrado else encode(extensions.pgp_sym_encrypt(v_nss,p_clave_datos,'cipher-algo=aes256'),'base64') end,
    f_nss_hash=case when v_nss is null then f_nss_hash else v_nss_hash end,
    f_nss_mascara=case when v_nss is null then f_nss_mascara else '***'||right(v_nss,4) end,
    f_fecha_nacimiento=p_fecha_nacimiento,
    f_telefono_verificado_en=case when coalesce(p_telefono_verificado,false) then coalesce(f_telefono_verificado_en,now()) else null end,
    f_estado_seguimiento=p_estado_seguimiento,
    f_canal_contacto_preferido=p_canal_contacto,
    f_activo=coalesce(p_activo,false),
    f_actualizado_en=now()
  where f_uuid=p_paciente_uuid and f_idempresa=v_empresa and f_app=v_app;
  return p_paciente_uuid;
end $$;

alter table api.t_historial_identificadores_paciente enable row level security;
revoke all on api.t_historial_identificadores_paciente from public,anon,authenticated;
grant select,insert on api.t_historial_identificadores_paciente to service_role;

revoke all on function api.fn_consultar_identificadores_paciente(uuid,uuid,text) from public,anon,authenticated;
grant execute on function api.fn_consultar_identificadores_paciente(uuid,uuid,text) to service_role;
revoke all on function api.fn_actualizar_paciente(uuid,uuid,text,text,text,uuid,text,text,date,boolean,text,text,boolean,text) from public,anon,authenticated;
grant execute on function api.fn_actualizar_paciente(uuid,uuid,text,text,text,uuid,text,text,date,boolean,text,text,boolean,text) to service_role;

notify pgrst, 'reload schema';

commit;
